from __future__ import annotations

import json
from pathlib import Path
import unittest


ROOT = Path(__file__).resolve().parents[1]


def recipe_body(justfile: str, name: str) -> str:
    lines = justfile.splitlines()
    body: list[str] = []
    capturing = False
    for line in lines:
        if capturing:
            if line.startswith("#") or line.startswith(" ") or line.startswith("\t") or line.strip() == "":
                body.append(line)
                continue
            break
        if line == f"{name}:" or line.startswith(f"{name}:"):
            capturing = True
    return "\n".join(body)


class DesktopShellTests(unittest.TestCase):
    def test_html_lang_is_zh_cn(self):
        html = (ROOT / "apps/bmdock-desktop/index.html").read_text(encoding="utf-8")
        self.assertIn('lang="zh-CN"', html)

    def test_just_dev_switches_to_tauri_and_build_stays_probe(self):
        justfile = (ROOT / "justfile").read_text(encoding="utf-8")
        dev = recipe_body(justfile, "dev")
        build = recipe_body(justfile, "build")
        contract = recipe_body(justfile, "contract")
        contract_main = recipe_body(justfile, "contract-main")
        tauri_dev = recipe_body(justfile, "tauri-dev")
        tauri_build = recipe_body(justfile, "tauri-build")
        self.assertIn("tauri-dev", dev)
        self.assertNotIn('main(["dev"', dev)
        self.assertIn('main(["build"])', build)
        self.assertNotIn("tauri", build.lower())
        self.assertIn('main(["contract", "release"])', contract)
        self.assertIn('main(["contract", "main-preview"])', contract_main)
        self.assertIn("tauri:dev", tauri_dev)
        self.assertIn("tauri:build", tauri_build)

    def test_agent_docs_match_just_dev_tauri_and_build_probe(self):
        for name in ("AGENTS.md", "CLAUDE.md"):
            text = (ROOT / name).read_text(encoding="utf-8")
            self.assertIn("just tauri-dev", text)
            self.assertIn("just tauri-build", text)
            self.assertIn("just contract", text)
            self.assertIn("just dev-main", text)
            self.assertRegex(
                text,
                r"(?is)just dev.{0,300}(tauri-dev|tauri 桌面|desktop shell|desktop layout)",
                msg=f"{name} must describe just dev as the Tauri desktop shell",
            )
            self.assertRegex(
                text,
                r"(?is)just build.{0,240}(bmdock-probe|g0 probe|g0 探针)",
                msg=f"{name} must describe just build as the G0 probe",
            )

    def test_ci_still_builds_g0_probe_via_just_build(self):
        workflow = (ROOT / ".github/workflows/ci.yml").read_text(encoding="utf-8")
        self.assertIn("just build", workflow)

    def test_chinese_nav_catalog_and_no_i18n_dependency(self):
        catalog = (ROOT / "apps/bmdock-desktop/src/i18n.ts").read_text(encoding="utf-8")
        self.assertIn('export const LOCALE = "zh-CN"', catalog)
        self.assertIn("工作台", catalog)
        self.assertIn("运行状态", catalog)
        self.assertIn("预检", catalog)
        self.assertIn("项目", catalog)
        self.assertIn("维护", catalog)
        self.assertIn("导入", catalog)
        self.assertIn("Extra / 文档摄取", catalog)
        self.assertIn("观察", catalog)
        self.assertIn("关系", catalog)
        self.assertIn("图谱", catalog)
        self.assertIn("检索", catalog)
        self.assertIn("基准", catalog)
        self.assertIn("Schema 工作台", catalog)
        self.assertIn("资源", catalog)
        self.assertIn("提示词", catalog)
        self.assertIn("工具", catalog)
        self.assertIn("CLI 任务中心", catalog)
        self.assertIn("运行时", catalog)
        self.assertIn("说明", catalog)
        package = json.loads((ROOT / "apps/bmdock-desktop/package.json").read_text(encoding="utf-8"))
        deps = {**package.get("dependencies", {}), **package.get("devDependencies", {})}
        for name in deps:
            self.assertNotIn("i18n", name.lower())

    def test_landmarks_empty_error_and_no_writes(self):
        app = (ROOT / "apps/bmdock-desktop/src/App.tsx").read_text(encoding="utf-8")
        shell = (ROOT / "apps/bmdock-desktop/src/shell.ts").read_text(encoding="utf-8")
        styles = (ROOT / "apps/bmdock-desktop/src/styles.css").read_text(encoding="utf-8")
        catalog = (ROOT / "apps/bmdock-desktop/src/i18n.ts").read_text(encoding="utf-8")
        main = (ROOT / "apps/bmdock-desktop/src/main.tsx").read_text(encoding="utf-8")
        self.assertIn("<header", app)
        self.assertIn("<nav", app)
        self.assertIn("<main", app)
        self.assertIn('href="#main"', app)
        self.assertIn("skip-link", app)
        self.assertIn("aria-current", app)
        self.assertIn("aria-label", app)
        self.assertIn('data-state="empty"', app)
        self.assertIn('data-state="error"', app)
        self.assertIn("workbenchErrorTitle", app)
        self.assertIn("capabilities.policy.project", app)
        self.assertIn(":focus-visible", styles)
        self.assertIn("document.documentElement.lang", main)
        self.assertIn("emptyBadge", catalog)
        self.assertIn("errorBadge", catalog)
        self.assertIn("unexpectedCapabilities", catalog)
        self.assertIn("unexpectedRuntime", catalog)
        self.assertIn("unexpectedCatalog", catalog)
        self.assertIn("unexpectedPreflight", catalog)
        self.assertIn("unexpectedDiscovery", catalog)
        self.assertIn("unexpectedBackups", catalog)
        self.assertIn("unexpectedRestore", catalog)
        self.assertIn("unexpectedImport", catalog)
        self.assertIn("unexpectedWindowsRuntime", catalog)
        self.assertIn("unexpectedDraft", catalog)
        self.assertIn("unexpectedCrud", catalog)
        self.assertIn("unexpectedRelations", catalog)
        self.assertIn("unexpectedGraph", catalog)
        self.assertIn("unexpectedSearch", catalog)
        self.assertIn("unexpectedResources", catalog)
        self.assertIn("unexpectedPrompts", catalog)
        self.assertIn("unexpectedTools", catalog)
        self.assertIn("unexpectedCli", catalog)
        self.assertIn("searchEmptyTitle", catalog)
        self.assertIn("searchErrorTitle", catalog)
        self.assertIn("searchReadyTitle", catalog)
        self.assertIn("unexpectedDrain", catalog)
        self.assertIn("runtimeDrainStart", catalog)
        self.assertIn("runtimeDrainIdle", catalog)
        self.assertIn("runtimeDrainDraining", catalog)
        self.assertIn("draftEmptyTitle", catalog)
        self.assertIn("draftErrorTitle", catalog)
        self.assertIn("draftReadyTitle", catalog)
        self.assertIn("draftIdentifierLabel", catalog)
        self.assertIn("draftBodyLabel", catalog)
        self.assertIn("contentSafetyTitle", catalog)
        self.assertIn("contentSafetyExecutedNo", catalog)
        self.assertIn("contentSafetyImeUnverified", catalog)
        self.assertIn("contentSafetyHelpNotT39", catalog)
        self.assertIn("draftSave", catalog)
        self.assertIn("draftReload", catalog)
        self.assertIn("draftSessionDirty", catalog)
        self.assertIn("draftSessionDisk", catalog)
        self.assertIn("draftEnginePersistedLabel", catalog)
        self.assertIn("crudEmptyTitle", catalog)
        self.assertIn("crudErrorTitle", catalog)
        self.assertIn("crudReadyTitle", catalog)
        self.assertIn("crudWrite", catalog)
        self.assertIn("crudEdit", catalog)
        self.assertIn("crudMove", catalog)
        self.assertIn("crudDelete", catalog)
        self.assertIn("crudDeleteConfirm", catalog)
        self.assertIn("windowsEmptyTitle", catalog)
        self.assertIn("windowsErrorTitle", catalog)
        self.assertIn("windowsReadyTitle", catalog)
        self.assertIn("windowsObservedTitle", catalog)
        self.assertIn("windowsUnverifiedTitle", catalog)
        self.assertIn("discoveryEmptyTitle", catalog)
        self.assertIn("backupsEmptyTitle", catalog)
        self.assertIn("backupsErrorTitle", catalog)
        self.assertIn("backupsReadyTitle", catalog)
        self.assertIn("importEmptyTitle", catalog)
        self.assertIn("importErrorTitle", catalog)
        self.assertIn("importReadyTitle", catalog)
        self.assertIn("extrasEmptyTitle", catalog)
        self.assertIn("extrasErrorTitle", catalog)
        self.assertIn("extrasReadyTitle", catalog)
        self.assertIn("backupsRestore", catalog)
        self.assertIn("projectsEmptyNoneSelectedTitle", catalog)
        self.assertIn("projectsEmptyNoneFoundTitle", catalog)
        self.assertIn("projectsErrorTitle", catalog)
        self.assertIn("projectsReadyTitle", catalog)
        self.assertIn('t("unexpectedCapabilities")', shell)
        self.assertIn('t("unexpectedRuntime")', shell)
        self.assertIn("get_capabilities", shell)
        self.assertIn("get_runtime_state", shell)
        self.assertIn("list_projects", shell)
        self.assertIn("run_preflight", shell)
        self.assertIn("discover_config", shell)
        self.assertNotIn("list_tree", shell)
        self.assertNotIn("read_note", shell)
        self.assertNotIn("list_backups", shell)
        self.assertNotIn("restore_fixture", shell)
        self.assertNotIn("import_notes", shell)
        self.assertNotIn("inspect_api_audit", shell)
        self.assertNotIn("inspect_extras", shell)
        self.assertNotIn("ingest_document", shell)
        self.assertNotIn("inspect_windows_runtime", shell)
        self.assertNotIn("save_draft", shell)
        self.assertNotIn("load_draft", shell)
        self.assertNotIn("write_note", shell)
        self.assertNotIn("edit_note", shell)
        self.assertNotIn("move_note", shell)
        self.assertNotIn("delete_note", shell)
        self.assertNotIn("list_relations", shell)
        self.assertNotIn("expand_graph", shell)
        self.assertNotIn("search_notes", shell)
        self.assertNotIn("inspect_search", shell)
        self.assertNotIn("run_recall_benchmark", shell)
        self.assertNotIn("schema_validate", shell)
        self.assertNotIn("list_resources", shell)
        self.assertNotIn("list_prompts", shell)
        self.assertNotIn("preview_context", shell)
        self.assertNotIn("list_activity", shell)
        self.assertNotIn("begin_shutdown", shell)
        self.assertIn('t("unexpectedPreflight")', shell)
        self.assertIn('t("unexpectedDiscovery")', shell)
        self.assertIn('t("unexpectedCatalog")', shell)
        self.assertNotIn("select_project", shell)
        self.assertNotIn("callTool", shell)
        self.assertNotIn("call_tool", shell)
        self.assertNotIn("start_supervisor", shell)
        self.assertNotIn("stop_supervisor", shell)
        self.assertIn("select_project", app)
        self.assertNotIn("callTool", app)
        self.assertNotIn("start_supervisor", app)
        self.assertNotIn("stop_supervisor", app)
        self.assertIn("preflight", app)
        self.assertIn("projects", app)
        self.assertIn("backups", app)
        self.assertIn("import", app)
        self.assertIn("discoveryEmptyTitle", app)
        self.assertIn("projectsEmptyNoneSelectedTitle", app)
        self.assertIn("backupsEmptyTitle", app)
        self.assertIn("backupsRestore", app)
        self.assertIn('id.startsWith("fixture-")', app)
        self.assertIn("workbenchLoadMore", app)
        self.assertIn("workbenchPreviewTitle", app)
        self.assertIn("list_tree", app)
        self.assertIn("read_note", app)
        self.assertIn("list_relations", app)
        self.assertIn("expand_graph", app)
        self.assertIn("search_notes", app)
        self.assertIn("inspect_search", app)
        self.assertIn("run_recall_benchmark", app)
        self.assertIn("schema_validate", app)
        self.assertIn("list_resources", app)
        self.assertIn("list_prompts", app)
        self.assertIn("preview_context", app)
        self.assertIn("list_activity", app)
        self.assertIn("list_backups", app)
        self.assertIn("restore_fixture", app)
        self.assertIn("import_notes", app)
        self.assertIn("inspect_extras", app)
        self.assertIn("ingest_document", app)
        self.assertIn("inspect_windows_runtime", app)
        self.assertIn("save_draft", app)
        self.assertIn("load_draft", app)
        self.assertIn("write_note", app)
        self.assertIn("edit_note", app)
        self.assertIn("move_note", app)
        self.assertIn("delete_note", app)
        self.assertIn("begin_shutdown", app)
        self.assertIn("draftEmptyTitle", app)
        self.assertIn("draftErrorTitle", app)
        self.assertIn("draftReadyTitle", app)
        self.assertIn("contentSafetyTitle", app)
        self.assertIn('data-preview="text"', app)
        self.assertIn('data-executed="false"', app)
        self.assertIn("classifyBody", app)
        self.assertIn("crudEmptyTitle", app)
        self.assertIn("crudErrorTitle", app)
        self.assertIn("crudReadyTitle", app)
        self.assertIn('htmlFor="draft-identifier"', app)
        self.assertIn('htmlFor="draft-body"', app)
        self.assertIn('id="draft-identifier"', app)
        self.assertIn('id="draft-body"', app)
        self.assertIn('htmlFor="crud-identifier"', app)
        self.assertIn('htmlFor="crud-title"', app)
        self.assertIn('htmlFor="crud-body"', app)
        self.assertIn('htmlFor="crud-destination"', app)
        self.assertIn('id="crud-identifier"', app)
        self.assertIn('id="crud-body"', app)
        self.assertIn("<textarea", app)
        self.assertIn("draft-body", app)
        self.assertIn("crud-body", app)
        self.assertIn("draftSessionDirty", app)
        self.assertIn("engine_persisted", app)
        self.assertIn("copyFixtureRoute", app)
        self.assertIn("windowsEmptyTitle", app)
        self.assertIn("windowsErrorTitle", app)
        self.assertIn("windowsReadyTitle", app)
        self.assertIn("windowsObservedTitle", app)
        self.assertIn("windowsUnverifiedTitle", app)
        self.assertIn("copyFixtureRoute", app)
        self.assertIn("nextCursor", app)
        self.assertIn("note-body", app)
        self.assertIn("<pre", app)
        self.assertNotIn("dangerouslySetInnerHTML", app)
        self.assertNotIn("innerHTML", app)
        ipc = (ROOT / "apps/bmdock-desktop/src/ipc.ts").read_text(encoding="utf-8")
        self.assertIn("run_preflight", ipc)
        self.assertIn("discover_config", ipc)
        self.assertIn("list_projects", ipc)
        self.assertIn("list_tree", ipc)
        self.assertIn("read_note", ipc)
        self.assertIn("list_relations", ipc)
        self.assertIn("expand_graph", ipc)
        self.assertIn("search_notes", ipc)
        self.assertIn("inspect_search", ipc)
        self.assertIn("run_recall_benchmark", ipc)
        self.assertIn("schema_validate", ipc)
        self.assertIn("list_resources", ipc)
        self.assertIn("list_prompts", ipc)
        self.assertIn("preview_context", ipc)
        self.assertIn("list_activity", ipc)
        self.assertIn("list_backups", ipc)
        self.assertIn("restore_fixture", ipc)
        self.assertIn("import_notes", ipc)
        self.assertIn("inspect_api_audit", ipc)
        self.assertIn("inspect_extras", ipc)
        self.assertIn("ingest_document", ipc)
        self.assertIn("inspect_windows_runtime", ipc)
        self.assertIn("save_draft", ipc)
        self.assertIn("load_draft", ipc)
        self.assertIn("write_note", ipc)
        self.assertIn("edit_note", ipc)
        self.assertIn("move_note", ipc)
        self.assertIn("delete_note", ipc)
        self.assertIn("begin_shutdown", ipc)
        self.assertIn("engine_persisted", ipc)
        self.assertIn("webview2_files_present", ipc)
        self.assertIn("webview2_session_verified", ipc)
        self.assertIn("job_object_assigned", ipc)
        self.assertIn("job_object_api_documented", ipc)
        self.assertIn("installer_bundle_active", ipc)
        self.assertIn("ExplicitRouteArgs", ipc)
        self.assertIn("copyFixtureRoute", ipc)
        self.assertNotIn('command: "call_tool"', ipc)
        self.assertNotIn('"call_tool"', ipc)
        self.assertIn('command: "search_notes"', ipc)
        self.assertIn('command: "inspect_search"', ipc)
        self.assertIn('command: "run_recall_benchmark"', ipc)
        self.assertIn('command: "schema_validate"', ipc)
        self.assertIn('command: "list_resources"', ipc)
        self.assertIn('command: "list_prompts"', ipc)
        self.assertIn('command: "preview_context"', ipc)
        self.assertIn('command: "list_activity"', ipc)
        self.assertNotIn('{ command: "search"; args', ipc)
        self.assertIn('command: "write_note"', ipc)
        self.assertIn('command: "edit_note"', ipc)
        self.assertIn('command: "move_note"', ipc)
        self.assertIn('command: "delete_note"', ipc)
        self.assertIn("host.engine_spawned", app)
        self.assertIn("host.files_written", app)
        self.assertIn("arbitrary_paths_allowed", ipc)
        self.assertIn("raw_call_tool_allowed", ipc)
        self.assertIn("implicit_current_project_writes", ipc)
        self.assertIn("cross_project_search_allowed", ipc)
        self.assertIn("cloud_or_credential_required", ipc)
        self.assertIn("bmdock-workspace", ipc)
        self.assertIn("bmdock-fixture", ipc)
        self.assertIn("scanned_user_obsidian_vault", ipc)
        self.assertIn("scanned_user_basic_memory_home", ipc)

    def test_windows_runtime_prototype_is_unsigned_and_unbundled(self):
        conf = json.loads(
            (ROOT / "apps/bmdock-desktop/src-tauri/tauri.conf.json").read_text(encoding="utf-8")
        )
        self.assertFalse(conf["bundle"]["active"])
        ipc = (ROOT / "apps/bmdock-desktop/src/ipc.ts").read_text(encoding="utf-8")
        rust = (ROOT / "apps/bmdock-desktop/src-tauri/src/windows_runtime.rs").read_text(
            encoding="utf-8"
        )
        app = (ROOT / "apps/bmdock-desktop/src/App.tsx").read_text(encoding="utf-8")
        self.assertIn("inspect_windows_runtime", ipc)
        self.assertIn("webview2_session_verified: false", rust)
        self.assertIn("job_object_assigned: false", rust)
        self.assertIn("compiled exe / npm build / cargo test are not a native GUI", rust)
        self.assertIn("WebView2 files present is not a WebView2 session", rust)
        self.assertIn("Job Object API/docs is not proof a job was created", rust)
        self.assertIn("inspect_dto_is_not_just_contract", rust)
        self.assertIn("inspect_dto_is_not_t12_fixture_restore", rust)
        self.assertIn("windowsObservedTitle", app)
        self.assertIn("windowsUnverifiedTitle", app)
        self.assertNotIn("dangerouslySetInnerHTML", app)
        self.assertNotIn("start_supervisor", app)
        rust_ipc = (ROOT / "apps/bmdock-desktop/src-tauri/src/ipc.rs").read_text(encoding="utf-8")
        self.assertIn("InspectWindowsRuntime", rust_ipc)
        self.assertIn("SaveDraft", rust_ipc)
        self.assertIn("LoadDraft", rust_ipc)
        self.assertIn("WriteNote", rust_ipc)
        self.assertIn("EditNote", rust_ipc)
        self.assertIn("MoveNote", rust_ipc)
        self.assertIn("DeleteNote", rust_ipc)
        self.assertIn("ListRelations", rust_ipc)
        self.assertIn("ExpandGraph", rust_ipc)
        self.assertIn("SearchNotes", rust_ipc)
        self.assertIn("InspectSearch", rust_ipc)
        self.assertIn("RunRecallBenchmark", rust_ipc)
        self.assertIn("SchemaValidate", rust_ipc)
        self.assertIn("ListResources", rust_ipc)
        self.assertIn("ListPrompts", rust_ipc)
        self.assertIn("PreviewContext", rust_ipc)
        self.assertIn("ListActivity", rust_ipc)
        self.assertIn("InspectApiAudit", rust_ipc)
        self.assertIn("InspectExtras", rust_ipc)
        self.assertIn("IngestDocument", rust_ipc)
        self.assertIn("BeginShutdown", rust_ipc)
        self.assertIn("assert_eq!(capabilities.commands.len(), 34)", rust_ipc)
        self.assertNotIn("assert_eq!(capabilities.commands.len(), 32)", rust_ipc)
        self.assertNotIn("assert_eq!(capabilities.commands.len(), 28)", rust_ipc)
        self.assertNotIn("assert_eq!(capabilities.commands.len(), 26)", rust_ipc)
        self.assertNotIn("assert_eq!(capabilities.commands.len(), 23)", rust_ipc)
        self.assertNotIn("assert_eq!(capabilities.commands.len(), 21)", rust_ipc)
        self.assertNotIn("assert_eq!(capabilities.commands.len(), 19)", rust_ipc)
        self.assertNotIn("assert_eq!(capabilities.commands.len(), 18)", rust_ipc)
        self.assertNotIn("assert_eq!(capabilities.commands.len(), 17)", rust_ipc)
        self.assertNotIn("assert_eq!(capabilities.commands.len(), 13)", rust_ipc)

    def test_draft_editor_session_is_not_engine_write(self):
        app = (ROOT / "apps/bmdock-desktop/src/App.tsx").read_text(encoding="utf-8")
        ipc = (ROOT / "apps/bmdock-desktop/src/ipc.ts").read_text(encoding="utf-8")
        rust_ipc = (ROOT / "apps/bmdock-desktop/src-tauri/src/ipc.rs").read_text(encoding="utf-8")
        drafts = (ROOT / "apps/bmdock-desktop/src-tauri/src/drafts.rs").read_text(encoding="utf-8")
        catalog = (ROOT / "apps/bmdock-desktop/src/i18n.ts").read_text(encoding="utf-8")
        styles = (ROOT / "apps/bmdock-desktop/src/styles.css").read_text(encoding="utf-8")
        self.assertIn("save_draft", ipc)
        self.assertIn("load_draft", ipc)
        self.assertIn('command: "save_draft"', ipc)
        self.assertIn('command: "load_draft"', ipc)
        self.assertIn('command: "write_note"', ipc)
        self.assertNotIn("callTool", app)
        self.assertIn("write_note", app)
        self.assertIn("save_draft", app)
        self.assertIn("command: \"save_draft\"", app)
        self.assertNotIn("start_supervisor", app)
        self.assertNotIn("stop_supervisor", app)
        self.assertNotIn("dangerouslySetInnerHTML", app)
        self.assertIn("<textarea", app)
        self.assertIn('htmlFor="draft-body"', app)
        self.assertIn("engine_persisted: false", drafts)
        self.assertIn("engine_persisted", rust_ipc)
        self.assertIn("UNSUPPORTED_DRAFT_UNAVAILABLE", drafts)
        self.assertIn("engine/draft store unavailable", drafts)
        self.assertNotIn("engine/library unavailable", drafts)
        self.assertIn("[[欢迎]]", rust_ipc)
        self.assertIn("bmdock-t14", drafts)
        self.assertIn("bmdock-t15", rust_ipc)
        self.assertIn("envelope_is_not_disk_proof", drafts)
        self.assertIn("DraftClass::DiskVerified", rust_ipc)
        self.assertIn("DraftClass::AcceptedUnverified", rust_ipc)
        self.assertIn("draftSessionDirty", catalog)
        self.assertIn("draftSessionDisk", catalog)
        self.assertIn("draftEnginePersistedLabel", catalog)
        self.assertIn(":focus-visible", styles)
        self.assertIn(".draft-body", styles)

    def test_note_crud_is_typed_fixture_only_and_not_raw_call_tool(self):
        app = (ROOT / "apps/bmdock-desktop/src/App.tsx").read_text(encoding="utf-8")
        ipc = (ROOT / "apps/bmdock-desktop/src/ipc.ts").read_text(encoding="utf-8")
        rust_ipc = (ROOT / "apps/bmdock-desktop/src-tauri/src/ipc.rs").read_text(encoding="utf-8")
        library = (ROOT / "apps/bmdock-desktop/src-tauri/src/library.rs").read_text(encoding="utf-8")
        catalog = (ROOT / "apps/bmdock-desktop/src/i18n.ts").read_text(encoding="utf-8")
        styles = (ROOT / "apps/bmdock-desktop/src/styles.css").read_text(encoding="utf-8")
        self.assertIn('command: "write_note"', ipc)
        self.assertIn('command: "edit_note"', ipc)
        self.assertIn('command: "move_note"', ipc)
        self.assertIn('command: "delete_note"', ipc)
        self.assertNotIn('command: "call_tool"', ipc)
        self.assertNotIn("callTool", app)
        self.assertNotIn("start_supervisor", app)
        self.assertNotIn("stop_supervisor", app)
        self.assertNotIn("dangerouslySetInnerHTML", app)
        self.assertIn("crudDeleteConfirm", app)
        self.assertIn("isFixtureNoteIdentifier", app)
        self.assertIn("copyFixtureRoute", app)
        self.assertIn("engine_persisted: false", library)
        self.assertIn("UNSUPPORTED_LIBRARY_UNAVAILABLE", library)
        self.assertIn("engine/library unavailable", library)
        self.assertIn("UNSUPPORTED_MOVE_DESTINATION_EXISTS", library)
        self.assertIn("sequential dest-exists is unsupported and is not T16", library)
        self.assertNotIn("concurrent overwrite remains UNVERIFIED", library)
        self.assertIn("bmdock-t15", library)
        self.assertIn("NoteCrudClass::DiskVerified", rust_ipc)
        self.assertIn("NoteCrudClass::AcceptedUnverified", rust_ipc)
        self.assertIn("[[欢迎]]", rust_ipc)
        self.assertIn("implicit_current_project_writes", rust_ipc)
        self.assertIn("crudWrite", catalog)
        self.assertIn("crudEdit", catalog)
        self.assertIn("crudMove", catalog)
        self.assertIn("crudDeleteConfirm", catalog)
        self.assertIn(".crud-body", styles)
        self.assertIn("command: \"save_draft\"", app)
        self.assertIn("command: \"write_note\"", app)

    def test_conflict_and_timeout_unknown_stay_distinct(self):
        app = (ROOT / "apps/bmdock-desktop/src/App.tsx").read_text(encoding="utf-8")
        ipc = (ROOT / "apps/bmdock-desktop/src/ipc.ts").read_text(encoding="utf-8")
        rust_ipc = (ROOT / "apps/bmdock-desktop/src-tauri/src/ipc.rs").read_text(encoding="utf-8")
        conflict = (ROOT / "apps/bmdock-desktop/src-tauri/src/conflict.rs").read_text(
            encoding="utf-8"
        )
        library = (ROOT / "apps/bmdock-desktop/src-tauri/src/library.rs").read_text(encoding="utf-8")
        catalog = (ROOT / "apps/bmdock-desktop/src/i18n.ts").read_text(encoding="utf-8")
        styles = (ROOT / "apps/bmdock-desktop/src/styles.css").read_text(encoding="utf-8")
        shell = (ROOT / "apps/bmdock-desktop/src/shell.ts").read_text(encoding="utf-8")
        self.assertIn("library::NoteCrudClass::Conflict", rust_ipc)
        self.assertIn("NoteCrudClass::Conflict", conflict)
        self.assertIn("| \"conflict\"", ipc)
        self.assertIn('export type ErrorCategory = "policy" | "schema" | "unsupported"', ipc)
        self.assertNotIn('ErrorCategory = "policy" | "schema" | "unsupported" | "timeout_unknown"', ipc)
        self.assertIn('export type FailureKind = "policy" | "transport" | "timeout_unknown" | "process" | "unverified"', ipc)
        self.assertIn("auto_retry_non_idempotent_write", conflict)
        self.assertIn("should_auto_retry_non_idempotent_write", conflict)
        self.assertIn("OS_FILESYSTEM_RACE_UNVERIFIED", conflict)
        self.assertIn("RECOVERY_NOT_T16", conflict)
        self.assertIn("not an OS file lock", conflict)
        self.assertIn("crudObservationConflict", app)
        self.assertIn("failureTimeoutUnknown", app)
        self.assertIn("crudObservationDisk", app)
        self.assertIn("crudObservationUnverified", app)
        self.assertIn("coordination-legend", app)
        self.assertIn("data-observation", app)
        self.assertIn("crudTimeoutUnknownLabel", app)
        self.assertIn("crudRecoveryNotT17", app)
        self.assertNotIn("dangerouslySetInnerHTML", app)
        self.assertNotIn("start_supervisor", app)
        self.assertNotIn("stop_supervisor", app)
        self.assertIn('t("failureTimeoutUnknown")', shell)
        self.assertIn("crudObservationConflict", catalog)
        self.assertIn("failureTimeoutUnknown", catalog)
        self.assertNotEqual(catalog.count("crudObservationConflict"), 0)
        conflict_label = '观察分类：同目标冲突，不是磁盘已核对，也不是超时未知'
        disk_label = "观察分类：已核对物理笔记文件"
        unverified_label = "观察分类：仅信封成功，不能当作磁盘证据"
        timeout_label = "超时未知"
        self.assertIn(conflict_label, catalog)
        self.assertIn(disk_label, catalog)
        self.assertIn(unverified_label, catalog)
        self.assertIn(timeout_label, catalog)
        self.assertNotEqual(conflict_label, timeout_label)
        self.assertNotEqual(conflict_label, disk_label)
        self.assertNotEqual(conflict_label, unverified_label)
        self.assertNotEqual(timeout_label, disk_label)
        self.assertIn("sequential dest-exists is unsupported and is not T16", library)
        self.assertIn("Conflict", rust_ipc)
        self.assertIn("refuse_auto_retry", rust_ipc)
        self.assertIn(".coordination-legend", styles)
        self.assertIn("mod conflict", (ROOT / "apps/bmdock-desktop/src-tauri/src/main.rs").read_text(encoding="utf-8"))

    def test_graceful_exit_drain_is_distinct_and_does_not_start_supervisor(self):
        app = (ROOT / "apps/bmdock-desktop/src/App.tsx").read_text(encoding="utf-8")
        ipc = (ROOT / "apps/bmdock-desktop/src/ipc.ts").read_text(encoding="utf-8")
        rust_ipc = (ROOT / "apps/bmdock-desktop/src-tauri/src/ipc.rs").read_text(encoding="utf-8")
        drain = (ROOT / "apps/bmdock-desktop/src-tauri/src/drain.rs").read_text(encoding="utf-8")
        catalog = (ROOT / "apps/bmdock-desktop/src/i18n.ts").read_text(encoding="utf-8")
        styles = (ROOT / "apps/bmdock-desktop/src/styles.css").read_text(encoding="utf-8")
        shell = (ROOT / "apps/bmdock-desktop/src/shell.ts").read_text(encoding="utf-8")
        main = (ROOT / "apps/bmdock-desktop/src-tauri/src/main.rs").read_text(encoding="utf-8")
        self.assertIn('command: "begin_shutdown"', ipc)
        self.assertIn("host_drain", ipc)
        self.assertIn("idle_not_started", ipc)
        self.assertIn("inflight_unknown", ipc)
        self.assertIn("BeginShutdown", rust_ipc)
        self.assertIn("UNSUPPORTED_HOST_DRAINING", drain)
        self.assertIn("host is draining", drain)
        self.assertIn("FORCED_KILL_UNVERIFIED", drain)
        self.assertIn("JOB_OBJECT_UNVERIFIED", drain)
        self.assertIn("SLEEP_RESUME_UNVERIFIED", drain)
        self.assertIn("DISK_FAILURE_UNVERIFIED", drain)
        self.assertIn("T12_RESTORE_IS_NOT_T17_DRAIN", drain)
        self.assertIn("T16_CONFLICT_IS_NOT_T17_DRAIN", drain)
        self.assertIn("T07_FAKES_ARE_NOT_NATIVE_PROCESS_TREE", drain)
        self.assertIn("not a native process-tree", drain)
        self.assertIn("mod drain", main)
        self.assertIn("begin_shutdown", app)
        self.assertIn("runtimeDrainStart", app)
        self.assertIn("runtimeDrainIdleLabel", app)
        self.assertIn("runtimeDrainDrainingLabel", app)
        self.assertIn("runtimeDrainTimeoutUnknownLabel", app)
        self.assertIn("runtimeDrainConflictLabel", app)
        self.assertIn("data-drain", app)
        self.assertNotIn("dangerouslySetInnerHTML", app)
        self.assertNotIn("start_supervisor", app)
        self.assertNotIn("stop_supervisor", app)
        self.assertNotIn("begin_shutdown", shell)
        self.assertIn("drainPhaseLabel", shell)
        idle_label = "空闲（尚未排空）"
        draining_label = "正在排空（拒绝新的笔记写入）"
        timeout_label = "超时未知（运行状态失败分类）"
        conflict_label = "同目标冲突（工作台 CRUD，不是本排空收据）"
        self.assertIn(idle_label, catalog)
        self.assertIn(draining_label, catalog)
        self.assertIn(timeout_label, catalog)
        self.assertIn(conflict_label, catalog)
        self.assertNotEqual(idle_label, draining_label)
        self.assertNotEqual(idle_label, timeout_label)
        self.assertNotEqual(idle_label, conflict_label)
        self.assertNotEqual(draining_label, timeout_label)
        self.assertNotEqual(draining_label, conflict_label)
        self.assertNotEqual(timeout_label, conflict_label)
        self.assertIn(".drain-legend", styles)
        self.assertIn("assert_eq!(capabilities.commands.len(), 34)", rust_ipc)
        self.assertNotIn("assert_eq!(capabilities.commands.len(), 32)", rust_ipc)
        self.assertNotIn("assert_eq!(capabilities.commands.len(), 28)", rust_ipc)
        self.assertNotIn("assert_eq!(capabilities.commands.len(), 26)", rust_ipc)
        self.assertNotIn("assert_eq!(capabilities.commands.len(), 23)", rust_ipc)
        self.assertIn('| "conflict"', ipc)
        self.assertIn('export type ErrorCategory = "policy" | "schema" | "unsupported"', ipc)
        self.assertNotIn('ErrorCategory = "policy" | "schema" | "unsupported" | "timeout_unknown"', ipc)

    def test_editor_content_safety_and_windows_roundtrip(self):
        app = (ROOT / "apps/bmdock-desktop/src/App.tsx").read_text(encoding="utf-8")
        safety_ts = (ROOT / "apps/bmdock-desktop/src/contentSafety.ts").read_text(encoding="utf-8")
        catalog = (ROOT / "apps/bmdock-desktop/src/i18n.ts").read_text(encoding="utf-8")
        styles = (ROOT / "apps/bmdock-desktop/src/styles.css").read_text(encoding="utf-8")
        rust = (ROOT / "apps/bmdock-desktop/src-tauri/src/content_safety.rs").read_text(
            encoding="utf-8"
        )
        drafts = (ROOT / "apps/bmdock-desktop/src-tauri/src/drafts.rs").read_text(encoding="utf-8")
        library = (ROOT / "apps/bmdock-desktop/src-tauri/src/library.rs").read_text(encoding="utf-8")
        rust_ipc = (ROOT / "apps/bmdock-desktop/src-tauri/src/ipc.rs").read_text(encoding="utf-8")
        main = (ROOT / "apps/bmdock-desktop/src-tauri/src/main.rs").read_text(encoding="utf-8")
        self.assertIn("classifyBody", safety_ts)
        self.assertIn("executed: false", safety_ts)
        self.assertIn("<script>", safety_ts)
        self.assertIn("onerror=", safety_ts)
        self.assertIn("[[欢迎]]", safety_ts)
        self.assertIn("\\r\\n", safety_ts)
        self.assertIn("UNSAFE_HTML_WIKI_CRLF_BODY", rust)
        self.assertIn("persist_exact_utf8", rust)
        self.assertIn("crlf_normalized_to_lf", rust)
        self.assertIn("not disk_verified", rust)
        self.assertIn("UNVERIFIED", rust)
        self.assertIn("T39", rust)
        self.assertIn("persist_exact_utf8", drafts)
        self.assertIn("persist_exact_utf8", library)
        self.assertIn("unsafe_html_crlf_wiki_roundtrips_on_draft_and_note_paths", rust_ipc)
        self.assertIn("mod content_safety", main)
        self.assertIn("classifyBody", app)
        self.assertIn("<textarea", app)
        self.assertIn("<pre", app)
        self.assertIn('data-preview="text"', app)
        self.assertIn('data-executed="false"', app)
        self.assertIn('htmlFor="draft-body"', app)
        self.assertIn('htmlFor="crud-body"', app)
        self.assertIn('id="draft-body"', app)
        self.assertIn('id="crud-body"', app)
        self.assertNotIn("dangerouslySetInnerHTML", app)
        self.assertNotIn("innerHTML", app)
        self.assertNotIn("start_supervisor", app)
        self.assertNotIn("stop_supervisor", app)
        self.assertNotIn("callTool", app)
        self.assertIn("contentSafetyTitle", catalog)
        self.assertIn("contentSafetyExecutedNo", catalog)
        self.assertIn("contentSafetyImeUnverified", catalog)
        self.assertIn("contentSafetyHelpNotT39", catalog)
        self.assertIn("T39", catalog)
        self.assertIn(":focus-visible", styles)
        self.assertIn(".content-safety", styles)
        self.assertIn("C:\\Users\\someone\\vault\\note.md", rust_ipc)
        self.assertIn("looks_like_filesystem_path", library)
        self.assertIn("assert_eq!(capabilities.commands.len(), 34)", rust_ipc)
        self.assertNotIn("assert_eq!(capabilities.commands.len(), 32)", rust_ipc)
        self.assertNotIn("assert_eq!(capabilities.commands.len(), 28)", rust_ipc)
        self.assertNotIn("assert_eq!(capabilities.commands.len(), 26)", rust_ipc)
        self.assertNotIn("assert_eq!(capabilities.commands.len(), 23)", rust_ipc)

    def test_observation_and_relation_panel_is_fixture_wiki_links_not_engine_graph(self):
        app = (ROOT / "apps/bmdock-desktop/src/App.tsx").read_text(encoding="utf-8")
        ipc = (ROOT / "apps/bmdock-desktop/src/ipc.ts").read_text(encoding="utf-8")
        rust_ipc = (ROOT / "apps/bmdock-desktop/src-tauri/src/ipc.rs").read_text(encoding="utf-8")
        library = (ROOT / "apps/bmdock-desktop/src-tauri/src/library.rs").read_text(encoding="utf-8")
        catalog = (ROOT / "apps/bmdock-desktop/src/i18n.ts").read_text(encoding="utf-8")
        styles = (ROOT / "apps/bmdock-desktop/src/styles.css").read_text(encoding="utf-8")
        self.assertIn('command: "list_relations"', ipc)
        self.assertIn("RelationListDto", ipc)
        self.assertIn("engine_graph: false", ipc)
        self.assertIn("ListRelations", rust_ipc)
        self.assertIn("assert_eq!(capabilities.commands.len(), 34)", rust_ipc)
        self.assertNotIn("assert_eq!(capabilities.commands.len(), 32)", rust_ipc)
        self.assertNotIn("assert_eq!(capabilities.commands.len(), 28)", rust_ipc)
        self.assertNotIn("assert_eq!(capabilities.commands.len(), 26)", rust_ipc)
        self.assertNotIn("assert_eq!(capabilities.commands.len(), 23)", rust_ipc)
        self.assertIn("extract_wiki_link_identifiers", library)
        self.assertIn("ENGINE_GRAPH_NOT_OWNED", library)
        self.assertIn("RECENT_ACTIVITY_MCP_UNVERIFIED", library)
        self.assertIn("BUILD_CONTEXT_MCP_UNVERIFIED", library)
        self.assertIn("official recent_activity MCP remains UNVERIFIED", library)
        self.assertIn("official build_context MCP remains UNVERIFIED", library)
        self.assertIn("empty_relation_list", library)
        self.assertIn("ObservationPanel", app)
        self.assertIn("RelationPanel", app)
        self.assertIn("list_relations", app)
        self.assertIn("observationDisk", app)
        self.assertIn("observationConflict", app)
        self.assertIn("observationUnverified", app)
        self.assertIn("observationEmpty", app)
        self.assertIn("observationDistinctFromRelations", app)
        self.assertIn("relationsPermalinkNotPath", app)
        self.assertIn("relationsMcpUnverified", app)
        self.assertIn("relationsEmptyTitle", catalog)
        self.assertIn("observationReadyTitle", catalog)
        disk_label = "已核对磁盘（disk_verified）"
        unverified_label = "仅信封成功（accepted_unverified）"
        conflict_label = "同目标冲突（conflict）"
        empty_label = "空态（empty）"
        self.assertIn(disk_label, catalog)
        self.assertIn(unverified_label, catalog)
        self.assertIn(conflict_label, catalog)
        self.assertIn(empty_label, catalog)
        self.assertNotEqual(disk_label, conflict_label)
        self.assertNotEqual(unverified_label, conflict_label)
        self.assertNotEqual(empty_label, conflict_label)
        self.assertIn("观察", catalog)
        self.assertIn("关系", catalog)
        self.assertNotIn("dangerouslySetInnerHTML", app)
        self.assertNotIn("innerHTML", app)
        self.assertNotIn("start_supervisor", app)
        self.assertNotIn("callTool", app)
        self.assertNotIn('command: "recent_activity"', ipc)
        self.assertNotIn('command: "build_context"', ipc)
        self.assertNotIn('command: "call_tool"', ipc)
        self.assertIn(".relation-list", styles)
        self.assertIn(".observation-legend", styles)
        self.assertIn("bmdock-t19", rust_ipc)

    def test_local_graph_progressive_expansion_is_fixture_wiki_links_not_engine_graph(self):
        app = (ROOT / "apps/bmdock-desktop/src/App.tsx").read_text(encoding="utf-8")
        ipc = (ROOT / "apps/bmdock-desktop/src/ipc.ts").read_text(encoding="utf-8")
        rust_ipc = (ROOT / "apps/bmdock-desktop/src-tauri/src/ipc.rs").read_text(encoding="utf-8")
        library = (ROOT / "apps/bmdock-desktop/src-tauri/src/library.rs").read_text(encoding="utf-8")
        catalog = (ROOT / "apps/bmdock-desktop/src/i18n.ts").read_text(encoding="utf-8")
        styles = (ROOT / "apps/bmdock-desktop/src/styles.css").read_text(encoding="utf-8")
        package = json.loads((ROOT / "apps/bmdock-desktop/package.json").read_text(encoding="utf-8"))
        deps = {**package.get("dependencies", {}), **package.get("devDependencies", {})}
        self.assertIn('command: "expand_graph"', ipc)
        self.assertIn("GraphPageDto", ipc)
        self.assertIn("engine_graph: false", ipc)
        self.assertIn("ExpandGraph", rust_ipc)
        self.assertIn("assert_eq!(capabilities.commands.len(), 34)", rust_ipc)
        self.assertNotIn("assert_eq!(capabilities.commands.len(), 32)", rust_ipc)
        self.assertNotIn("assert_eq!(capabilities.commands.len(), 28)", rust_ipc)
        self.assertNotIn("assert_eq!(capabilities.commands.len(), 26)", rust_ipc)
        self.assertNotIn("assert_eq!(capabilities.commands.len(), 23)", rust_ipc)
        self.assertNotIn("assert_eq!(capabilities.commands.len(), 19)", rust_ipc)
        self.assertIn("expand_graph", library)
        self.assertIn("empty_graph_page", library)
        self.assertIn("extract_wiki_link_identifiers", library)
        self.assertIn("ENGINE_GRAPH_NOT_OWNED", library)
        self.assertIn("NATIVE_GUI_UNVERIFIED", library)
        self.assertIn("BOUNDED_HOST_EXPANSION", library)
        self.assertIn("truncated inventory is not a success", library)
        self.assertIn("GraphPanel", app)
        self.assertIn("expand_graph", app)
        self.assertIn("graphLoadMore", app)
        self.assertIn("graphExpand", app)
        self.assertIn("next_cursor", app)
        self.assertIn("graphObservationDistinct", app)
        self.assertIn("graphEmptyTitle", catalog)
        self.assertIn("graphReadyTitle", catalog)
        self.assertIn("图谱", catalog)
        self.assertIn("欢迎", catalog)
        self.assertIn("graphChineseKept", catalog)
        self.assertNotIn("dangerouslySetInnerHTML", app)
        self.assertNotIn("innerHTML", app)
        self.assertNotIn("start_supervisor", app)
        self.assertNotIn("callTool", app)
        self.assertNotIn('command: "call_tool"', ipc)
        self.assertNotIn("vis.js", app)
        self.assertNotIn("vis-network", app)
        for name in deps:
            self.assertNotIn("vis", name.lower())
            self.assertNotIn("cytoscape", name.lower())
        self.assertIn(".graph-list", styles)
        self.assertIn("bmdock-t20", rust_ipc)
        self.assertNotIn(
            "expand_graph",
            (ROOT / "apps/bmdock-desktop/src/shell.ts").read_text(encoding="utf-8"),
        )
        self.assertNotIn("start_supervisor", rust_ipc)
        disk_label = "已核对磁盘（disk_verified）"
        conflict_label = "同目标冲突（conflict）"
        self.assertIn(disk_label, catalog)
        self.assertIn(conflict_label, catalog)
        self.assertNotEqual(disk_label, conflict_label)

    def test_hybrid_search_is_fixture_lexical_not_engine_semantic(self):
        app = (ROOT / "apps/bmdock-desktop/src/App.tsx").read_text(encoding="utf-8")
        ipc = (ROOT / "apps/bmdock-desktop/src/ipc.ts").read_text(encoding="utf-8")
        rust_ipc = (ROOT / "apps/bmdock-desktop/src-tauri/src/ipc.rs").read_text(encoding="utf-8")
        library = (ROOT / "apps/bmdock-desktop/src-tauri/src/library.rs").read_text(encoding="utf-8")
        catalog = (ROOT / "apps/bmdock-desktop/src/i18n.ts").read_text(encoding="utf-8")
        styles = (ROOT / "apps/bmdock-desktop/src/styles.css").read_text(encoding="utf-8")
        package = json.loads((ROOT / "apps/bmdock-desktop/package.json").read_text(encoding="utf-8"))
        deps = {**package.get("dependencies", {}), **package.get("devDependencies", {})}
        self.assertIn('command: "search_notes"', ipc)
        self.assertIn("SearchPageDto", ipc)
        self.assertIn("lexical_score", ipc)
        self.assertIn("semantic_score", ipc)
        self.assertIn("semantic_enabled: false", ipc)
        self.assertIn("engine_search: false", ipc)
        self.assertIn("SearchNotes", rust_ipc)
        self.assertIn("assert_eq!(capabilities.commands.len(), 34)", rust_ipc)
        self.assertNotIn("assert_eq!(capabilities.commands.len(), 32)", rust_ipc)
        self.assertNotIn("assert_eq!(capabilities.commands.len(), 28)", rust_ipc)
        self.assertNotIn("assert_eq!(capabilities.commands.len(), 26)", rust_ipc)
        self.assertNotIn("assert_eq!(capabilities.commands.len(), 23)", rust_ipc)
        self.assertNotIn("assert_eq!(capabilities.commands.len(), 20)", rust_ipc)
        self.assertIn("search_notes", library)
        self.assertIn("empty_search_page", library)
        self.assertIn("ENGINE_SEARCH_NOT_OWNED", library)
        self.assertIn("SEMANTIC_SEARCH_UNVERIFIED", library)
        self.assertIn("OFFICIAL_SEARCH_MCP_UNVERIFIED", library)
        self.assertIn("OFFICIAL_FETCH_MCP_UNVERIFIED", library)
        self.assertIn("POLICY_FILESYSTEM_QUERY", library)
        self.assertIn("SCHEMA_SEARCH_QUERY", library)
        self.assertIn("SearchPanel", app)
        self.assertIn("search_notes", app)
        self.assertIn('htmlFor="search-query"', app)
        self.assertIn('id="search-query"', app)
        self.assertIn("searchLexicalScore", app)
        self.assertIn("searchSemanticScore", app)
        self.assertIn("searchEmptyTitle", catalog)
        self.assertIn("searchErrorTitle", catalog)
        self.assertIn("searchReadyTitle", catalog)
        self.assertIn("检索", catalog)
        self.assertIn("词法分数", catalog)
        self.assertIn("语义分数", catalog)
        self.assertNotIn("dangerouslySetInnerHTML", app)
        self.assertNotIn("innerHTML", app)
        self.assertNotIn("start_supervisor", app)
        self.assertNotIn("callTool", app)
        self.assertNotIn('command: "call_tool"', ipc)
        self.assertNotIn('{ command: "search"; args', ipc)
        self.assertNotIn("vis.js", app)
        self.assertNotIn("vis-network", app)
        for name in deps:
            self.assertNotIn("vis", name.lower())
            self.assertNotIn("embedding", name.lower())
        self.assertIn(".search-list", styles)
        self.assertIn("bmdock-t21", rust_ipc)
        self.assertNotIn(
            "search_notes",
            (ROOT / "apps/bmdock-desktop/src/shell.ts").read_text(encoding="utf-8"),
        )
        self.assertNotIn("start_supervisor", rust_ipc)
        disk_label = "已核对磁盘（disk_verified）"
        empty_label = "空态（empty）"
        self.assertIn(disk_label, catalog)
        self.assertIn(empty_label, catalog)
        self.assertNotEqual(disk_label, empty_label)

    def test_context_preview_and_recent_activity_are_fixture_owned_not_engine_mcp(self):
        app = (ROOT / "apps/bmdock-desktop/src/App.tsx").read_text(encoding="utf-8")
        ipc = (ROOT / "apps/bmdock-desktop/src/ipc.ts").read_text(encoding="utf-8")
        rust_ipc = (ROOT / "apps/bmdock-desktop/src-tauri/src/ipc.rs").read_text(encoding="utf-8")
        library = (ROOT / "apps/bmdock-desktop/src-tauri/src/library.rs").read_text(encoding="utf-8")
        catalog = (ROOT / "apps/bmdock-desktop/src/i18n.ts").read_text(encoding="utf-8")
        styles = (ROOT / "apps/bmdock-desktop/src/styles.css").read_text(encoding="utf-8")
        package = json.loads((ROOT / "apps/bmdock-desktop/package.json").read_text(encoding="utf-8"))
        deps = {**package.get("dependencies", {}), **package.get("devDependencies", {})}
        self.assertIn('command: "preview_context"', ipc)
        self.assertIn('command: "list_activity"', ipc)
        self.assertIn("ContextPreviewDto", ipc)
        self.assertIn("ActivityPageDto", ipc)
        self.assertIn("executed: false", ipc)
        self.assertIn("engine_context: false", ipc)
        self.assertIn("engine_activity: false", ipc)
        self.assertIn("PreviewContext", rust_ipc)
        self.assertIn("ListActivity", rust_ipc)
        self.assertIn("assert_eq!(capabilities.commands.len(), 34)", rust_ipc)
        self.assertNotIn("assert_eq!(capabilities.commands.len(), 32)", rust_ipc)
        self.assertNotIn("assert_eq!(capabilities.commands.len(), 28)", rust_ipc)
        self.assertNotIn("assert_eq!(capabilities.commands.len(), 26)", rust_ipc)
        self.assertNotIn("assert_eq!(capabilities.commands.len(), 23)", rust_ipc)
        self.assertNotIn("assert_eq!(capabilities.commands.len(), 21)", rust_ipc)
        self.assertIn("preview_context", library)
        self.assertIn("list_activity", library)
        self.assertIn("empty_context_preview", library)
        self.assertIn("empty_activity_page", library)
        self.assertIn("ENGINE_CONTEXT_NOT_OWNED", library)
        self.assertIn("ENGINE_ACTIVITY_NOT_OWNED", library)
        self.assertIn("RECENT_ACTIVITY_MCP_UNVERIFIED", library)
        self.assertIn("BUILD_CONTEXT_MCP_UNVERIFIED", library)
        self.assertIn("ContextPreviewPanel", app)
        self.assertIn("ActivityPanel", app)
        self.assertIn("preview_context", app)
        self.assertIn("list_activity", app)
        self.assertIn('data-preview="text"', app)
        self.assertIn('data-executed="false"', app)
        self.assertIn("previewEmptyTitle", catalog)
        self.assertIn("previewErrorTitle", catalog)
        self.assertIn("previewReadyTitle", catalog)
        self.assertIn("activityEmptyTitle", catalog)
        self.assertIn("activityErrorTitle", catalog)
        self.assertIn("activityReadyTitle", catalog)
        self.assertIn("预览", catalog)
        self.assertIn("近期活动", catalog)
        self.assertNotIn("dangerouslySetInnerHTML", app)
        self.assertNotIn("innerHTML", app)
        self.assertNotIn("start_supervisor", app)
        self.assertNotIn("callTool", app)
        self.assertNotIn('command: "call_tool"', ipc)
        self.assertNotIn('command: "recent_activity"', ipc)
        self.assertNotIn('command: "build_context"', ipc)
        for name in deps:
            self.assertNotIn("vis", name.lower())
            self.assertNotIn("embedding", name.lower())
        self.assertIn(".activity-list", styles)
        self.assertIn("bmdock-t22", rust_ipc)
        self.assertNotIn(
            "preview_context",
            (ROOT / "apps/bmdock-desktop/src/shell.ts").read_text(encoding="utf-8"),
        )
        self.assertNotIn(
            "list_activity",
            (ROOT / "apps/bmdock-desktop/src/shell.ts").read_text(encoding="utf-8"),
        )
        self.assertNotIn("start_supervisor", rust_ipc)
        disk_label = "已核对磁盘（disk_verified）"
        empty_label = "空态（empty）"
        self.assertIn(disk_label, catalog)
        self.assertIn(empty_label, catalog)
        self.assertNotEqual(disk_label, empty_label)

    def test_search_inspector_explains_fixture_lexical_model_disabled(self):
        app = (ROOT / "apps/bmdock-desktop/src/App.tsx").read_text(encoding="utf-8")
        ipc = (ROOT / "apps/bmdock-desktop/src/ipc.ts").read_text(encoding="utf-8")
        rust_ipc = (ROOT / "apps/bmdock-desktop/src-tauri/src/ipc.rs").read_text(encoding="utf-8")
        library = (ROOT / "apps/bmdock-desktop/src-tauri/src/library.rs").read_text(encoding="utf-8")
        catalog = (ROOT / "apps/bmdock-desktop/src/i18n.ts").read_text(encoding="utf-8")
        styles = (ROOT / "apps/bmdock-desktop/src/styles.css").read_text(encoding="utf-8")
        package = json.loads((ROOT / "apps/bmdock-desktop/package.json").read_text(encoding="utf-8"))
        deps = {**package.get("dependencies", {}), **package.get("devDependencies", {})}
        self.assertIn('command: "inspect_search"', ipc)
        self.assertIn("SearchInspectorDto", ipc)
        self.assertIn("lexical_score", ipc)
        self.assertIn("semantic_score", ipc)
        self.assertIn("semantic_enabled: false", ipc)
        self.assertIn("model_loaded: false", ipc)
        self.assertIn('embedding_backend: EmbeddingBackend', ipc)
        self.assertIn('model_class: ModelClass', ipc)
        self.assertIn("semantic_model_loaded: false", ipc)
        self.assertIn("InspectSearch", rust_ipc)
        self.assertIn("assert_eq!(capabilities.commands.len(), 34)", rust_ipc)
        self.assertNotIn("assert_eq!(capabilities.commands.len(), 32)", rust_ipc)
        self.assertNotIn("assert_eq!(capabilities.commands.len(), 28)", rust_ipc)
        self.assertNotIn("assert_eq!(capabilities.commands.len(), 26)", rust_ipc)
        self.assertNotIn("assert_eq!(capabilities.commands.len(), 23)", rust_ipc)
        self.assertIn("inspect_search", library)
        self.assertIn("empty_search_inspector", library)
        self.assertIn("ENGINE_INSPECTOR_NOT_OWNED", library)
        self.assertIn("INSPECTOR_READ_ONLY", library)
        self.assertIn("INSPECTOR_MODEL_UNVERIFIED", library)
        self.assertIn("SEMANTIC_DISABLED_REASON", library)
        self.assertIn("SearchInspectorPanel", app)
        self.assertIn("inspect_search", app)
        self.assertIn('htmlFor="inspector-query"', app)
        self.assertIn('id="inspector-query"', app)
        self.assertIn("inspectorEmptyTitle", catalog)
        self.assertIn("inspectorErrorTitle", catalog)
        self.assertIn("inspectorReadyTitle", catalog)
        self.assertIn("检索 Inspector", catalog)
        self.assertIn("model_loaded=false", catalog)
        self.assertIn("semantic_model_loaded", app)
        self.assertNotIn("dangerouslySetInnerHTML", app)
        self.assertNotIn("innerHTML", app)
        self.assertNotIn("start_supervisor", app)
        self.assertNotIn("callTool", app)
        self.assertNotIn('command: "call_tool"', ipc)
        self.assertNotIn('{ command: "search"; args', ipc)
        for name in deps:
            self.assertNotIn("vis", name.lower())
            self.assertNotIn("embedding", name.lower())
        self.assertIn(".inspector-list", styles)
        self.assertIn("bmdock-t23", rust_ipc)
        self.assertNotIn(
            "inspect_search",
            (ROOT / "apps/bmdock-desktop/src/shell.ts").read_text(encoding="utf-8"),
        )
        self.assertNotIn("start_supervisor", rust_ipc)
        disk_label = "已核对磁盘（disk_verified）"
        empty_label = "空态（empty）"
        self.assertIn(disk_label, catalog)
        self.assertIn(empty_label, catalog)
        self.assertNotEqual(disk_label, empty_label)

    def test_chinese_recall_benchmark_is_fixture_disk_gold_not_native_gui(self):
        app = (ROOT / "apps/bmdock-desktop/src/App.tsx").read_text(encoding="utf-8")
        ipc = (ROOT / "apps/bmdock-desktop/src/ipc.ts").read_text(encoding="utf-8")
        rust_ipc = (ROOT / "apps/bmdock-desktop/src-tauri/src/ipc.rs").read_text(encoding="utf-8")
        library = (ROOT / "apps/bmdock-desktop/src-tauri/src/library.rs").read_text(encoding="utf-8")
        catalog = (ROOT / "apps/bmdock-desktop/src/i18n.ts").read_text(encoding="utf-8")
        styles = (ROOT / "apps/bmdock-desktop/src/styles.css").read_text(encoding="utf-8")
        package = json.loads((ROOT / "apps/bmdock-desktop/package.json").read_text(encoding="utf-8"))
        deps = {**package.get("dependencies", {}), **package.get("devDependencies", {})}
        self.assertIn('command: "run_recall_benchmark"', ipc)
        self.assertIn("RecallBenchmarkDto", ipc)
        self.assertIn("recall_hits", ipc)
        self.assertIn("recall_relevant", ipc)
        self.assertIn("search_elapsed_ms", ipc)
        self.assertIn("expand_elapsed_ms", ipc)
        self.assertIn("semantic_enabled: false", ipc)
        self.assertIn("engine_search: false", ipc)
        self.assertIn("native_gui: false", ipc)
        self.assertIn("RunRecallBenchmark", rust_ipc)
        self.assertIn("assert_eq!(capabilities.commands.len(), 34)", rust_ipc)
        self.assertNotIn("assert_eq!(capabilities.commands.len(), 32)", rust_ipc)
        self.assertNotIn("assert_eq!(capabilities.commands.len(), 28)", rust_ipc)
        self.assertNotIn("assert_eq!(capabilities.commands.len(), 26)", rust_ipc)
        self.assertNotIn("assert_eq!(capabilities.commands.len(), 24)", rust_ipc)
        self.assertIn("run_recall_benchmark", library)
        self.assertIn("empty_recall_benchmark", library)
        self.assertIn("ENGINE_RECALL_NOT_OWNED", library)
        self.assertIn("RECALL_NATIVE_UNVERIFIED", library)
        self.assertIn("OFFICIAL_CHINESE_RECALL_UNVERIFIED", library)
        self.assertIn("SCHEMA_RECALL_K", library)
        self.assertIn("CHINESE_RECALL_QUERIES", library)
        self.assertIn("RecallBenchmarkPanel", app)
        self.assertIn("run_recall_benchmark", app)
        self.assertIn('htmlFor="recall-k"', app)
        self.assertIn('id="recall-k"', app)
        self.assertIn("recallEmptyTitle", catalog)
        self.assertIn("recallErrorTitle", catalog)
        self.assertIn("recallReadyTitle", catalog)
        self.assertIn("基准", catalog)
        self.assertIn("recall@k", catalog)
        self.assertIn("native_gui=false", catalog)
        self.assertIn("欢迎", catalog)
        self.assertNotIn("dangerouslySetInnerHTML", app)
        self.assertNotIn("innerHTML", app)
        self.assertNotIn("start_supervisor", app)
        self.assertNotIn("callTool", app)
        self.assertNotIn('command: "call_tool"', ipc)
        self.assertNotIn('{ command: "search"; args', ipc)
        for name in deps:
            self.assertNotIn("vis", name.lower())
            self.assertNotIn("embedding", name.lower())
        self.assertIn(".benchmark-list", styles)
        self.assertIn("bmdock-t24", rust_ipc)
        self.assertNotIn(
            "run_recall_benchmark",
            (ROOT / "apps/bmdock-desktop/src/shell.ts").read_text(encoding="utf-8"),
        )
        self.assertNotIn("start_supervisor", rust_ipc)
        disk_label = "已核对磁盘（disk_verified）"
        empty_label = "空态（empty）"
        self.assertIn(disk_label, catalog)
        self.assertIn(empty_label, catalog)
        self.assertNotEqual(disk_label, empty_label)

    def test_schema_workbench_is_fixture_owned_not_official_mcp(self):
        app = (ROOT / "apps/bmdock-desktop/src/App.tsx").read_text(encoding="utf-8")
        ipc = (ROOT / "apps/bmdock-desktop/src/ipc.ts").read_text(encoding="utf-8")
        rust_ipc = (ROOT / "apps/bmdock-desktop/src-tauri/src/ipc.rs").read_text(encoding="utf-8")
        library = (ROOT / "apps/bmdock-desktop/src-tauri/src/library.rs").read_text(encoding="utf-8")
        catalog = (ROOT / "apps/bmdock-desktop/src/i18n.ts").read_text(encoding="utf-8")
        styles = (ROOT / "apps/bmdock-desktop/src/styles.css").read_text(encoding="utf-8")
        package = json.loads((ROOT / "apps/bmdock-desktop/package.json").read_text(encoding="utf-8"))
        deps = {**package.get("dependencies", {}), **package.get("devDependencies", {})}
        self.assertIn('command: "schema_validate"', ipc)
        self.assertIn("SchemaValidateDto", ipc)
        self.assertIn("SchemaVerdict", ipc)
        self.assertIn('verdict: SchemaVerdict', ipc)
        self.assertIn("observed_title", ipc)
        self.assertIn("observed_body", ipc)
        self.assertIn("engine_schema: false", ipc)
        self.assertIn("SchemaValidate", rust_ipc)
        self.assertIn("assert_eq!(capabilities.commands.len(), 34)", rust_ipc)
        self.assertNotIn("assert_eq!(capabilities.commands.len(), 32)", rust_ipc)
        self.assertNotIn("assert_eq!(capabilities.commands.len(), 28)", rust_ipc)
        self.assertNotIn("assert_eq!(capabilities.commands.len(), 26)", rust_ipc)
        self.assertNotIn("assert_eq!(capabilities.commands.len(), 25)", rust_ipc)
        self.assertIn("schema_validate", library)
        self.assertIn("empty_schema_report", library)
        self.assertIn("ENGINE_SCHEMA_NOT_OWNED", library)
        self.assertIn("OFFICIAL_SCHEMA_MCP_UNVERIFIED", library)
        self.assertIn("DEFAULT_SCHEMA_ID", library)
        self.assertIn("SchemaVerdict::Valid", library)
        self.assertIn("SchemaVerdict::Invalid", library)
        self.assertIn("SchemaWorkbenchPanel", app)
        self.assertIn("schema_validate", app)
        self.assertIn('htmlFor="schema-identifier"', app)
        self.assertIn('id="schema-identifier"', app)
        self.assertIn('htmlFor="schema-id"', app)
        self.assertIn('id="schema-id"', app)
        self.assertIn("schemaEmptyTitle", catalog)
        self.assertIn("schemaErrorTitle", catalog)
        self.assertIn("schemaReadyTitle", catalog)
        self.assertIn("Schema 工作台", catalog)
        self.assertIn("schema_validate / schema_infer / schema_diff", catalog)
        self.assertNotIn("dangerouslySetInnerHTML", app)
        self.assertNotIn("innerHTML", app)
        self.assertNotIn("start_supervisor", app)
        self.assertNotIn("callTool", app)
        self.assertNotIn('command: "call_tool"', ipc)
        self.assertNotIn('{ command: "schema_infer"; args', ipc)
        self.assertNotIn('{ command: "schema_diff"; args', ipc)
        for name in deps:
            self.assertNotIn("vis", name.lower())
            self.assertNotIn("ajv", name.lower())
        self.assertIn(".schema-list", styles)
        self.assertIn("bmdock-t25", rust_ipc)
        self.assertNotIn(
            "schema_validate",
            (ROOT / "apps/bmdock-desktop/src/shell.ts").read_text(encoding="utf-8"),
        )
        self.assertNotIn("start_supervisor", rust_ipc)
        valid_label = "有效（valid）"
        invalid_label = "无效（invalid）"
        empty_label = "空态（empty）"
        unsupported_label = "不受支持（unsupported）"
        self.assertIn(valid_label, catalog)
        self.assertIn(invalid_label, catalog)
        self.assertIn(empty_label, catalog)
        self.assertIn(unsupported_label, catalog)
        self.assertNotEqual(valid_label, invalid_label)
        self.assertNotEqual(empty_label, unsupported_label)

    def test_resources_and_prompts_workbench_is_fixture_owned_not_official_mcp(self):
        app = (ROOT / "apps/bmdock-desktop/src/App.tsx").read_text(encoding="utf-8")
        ipc = (ROOT / "apps/bmdock-desktop/src/ipc.ts").read_text(encoding="utf-8")
        rust_ipc = (ROOT / "apps/bmdock-desktop/src-tauri/src/ipc.rs").read_text(encoding="utf-8")
        library = (ROOT / "apps/bmdock-desktop/src-tauri/src/library.rs").read_text(encoding="utf-8")
        catalog = (ROOT / "apps/bmdock-desktop/src/i18n.ts").read_text(encoding="utf-8")
        styles = (ROOT / "apps/bmdock-desktop/src/styles.css").read_text(encoding="utf-8")
        package = json.loads((ROOT / "apps/bmdock-desktop/package.json").read_text(encoding="utf-8"))
        deps = {**package.get("dependencies", {}), **package.get("devDependencies", {})}
        self.assertIn('command: "list_resources"', ipc)
        self.assertIn('command: "list_prompts"', ipc)
        self.assertIn("ResourcePageDto", ipc)
        self.assertIn("PromptPageDto", ipc)
        self.assertIn("engine_resources: false", ipc)
        self.assertIn("engine_prompts: false", ipc)
        self.assertIn("ListResources", rust_ipc)
        self.assertIn("ListPrompts", rust_ipc)
        self.assertIn("assert_eq!(capabilities.commands.len(), 34)", rust_ipc)
        self.assertNotIn("assert_eq!(capabilities.commands.len(), 32)", rust_ipc)
        self.assertNotIn("assert_eq!(capabilities.commands.len(), 28)", rust_ipc)
        self.assertNotIn("assert_eq!(capabilities.commands.len(), 26)", rust_ipc)
        self.assertIn("list_resources", library)
        self.assertIn("list_prompts", library)
        self.assertIn("empty_resource_page", library)
        self.assertIn("empty_prompt_page", library)
        self.assertIn("ENGINE_RESOURCES_NOT_OWNED", library)
        self.assertIn("ENGINE_PROMPTS_NOT_OWNED", library)
        self.assertIn("OFFICIAL_RESOURCES_MCP_UNVERIFIED", library)
        self.assertIn("OFFICIAL_PROMPTS_MCP_UNVERIFIED", library)
        self.assertIn("PROMPT_SIDECAR_SUFFIX", library)
        self.assertIn("ResourceCatalogPanel", app)
        self.assertIn("PromptCatalogPanel", app)
        self.assertIn("list_resources", app)
        self.assertIn("list_prompts", app)
        self.assertIn("resourcesEmptyTitle", catalog)
        self.assertIn("resourcesErrorTitle", catalog)
        self.assertIn("resourcesReadyTitle", catalog)
        self.assertIn("promptsEmptyTitle", catalog)
        self.assertIn("promptsErrorTitle", catalog)
        self.assertIn("promptsReadyTitle", catalog)
        self.assertIn("资源", catalog)
        self.assertIn("提示词", catalog)
        self.assertIn("resources/list", catalog)
        self.assertIn("prompts/list", catalog)
        self.assertNotIn("dangerouslySetInnerHTML", app)
        self.assertNotIn("innerHTML", app)
        self.assertNotIn("start_supervisor", app)
        self.assertNotIn("callTool", app)
        self.assertNotIn('command: "call_tool"', ipc)
        self.assertNotIn('{ command: "resources/list"; args', ipc)
        self.assertNotIn('{ command: "prompts/list"; args', ipc)
        self.assertNotIn('{ command: "resources/read"; args', ipc)
        self.assertNotIn('{ command: "prompts/get"; args', ipc)
        for name in deps:
            self.assertNotIn("vis", name.lower())
            self.assertNotIn("ajv", name.lower())
        self.assertIn(".resource-list", styles)
        self.assertIn(".prompt-list", styles)
        self.assertIn("bmdock-t26", rust_ipc)
        self.assertNotIn(
            "list_resources",
            (ROOT / "apps/bmdock-desktop/src/shell.ts").read_text(encoding="utf-8"),
        )
        self.assertNotIn(
            "list_prompts",
            (ROOT / "apps/bmdock-desktop/src/shell.ts").read_text(encoding="utf-8"),
        )
        self.assertNotIn("start_supervisor", rust_ipc)
        self.assertNotEqual(t_label := "资源", t_prompt := "提示词")
        self.assertIn(t_label, catalog)
        self.assertIn(t_prompt, catalog)

    def test_controlled_tools_and_cli_center_are_catalog_only(self):
        app = (ROOT / "apps/bmdock-desktop/src/App.tsx").read_text(encoding="utf-8")
        ipc = (ROOT / "apps/bmdock-desktop/src/ipc.ts").read_text(encoding="utf-8")
        rust_ipc = (ROOT / "apps/bmdock-desktop/src-tauri/src/ipc.rs").read_text(encoding="utf-8")
        library = (ROOT / "apps/bmdock-desktop/src-tauri/src/library.rs").read_text(encoding="utf-8")
        catalog = (ROOT / "apps/bmdock-desktop/src/i18n.ts").read_text(encoding="utf-8")
        styles = (ROOT / "apps/bmdock-desktop/src/styles.css").read_text(encoding="utf-8")
        package = json.loads((ROOT / "apps/bmdock-desktop/package.json").read_text(encoding="utf-8"))
        deps = {**package.get("dependencies", {}), **package.get("devDependencies", {})}
        leaves = json.loads((ROOT / "compatibility/cli-leaves.json").read_text(encoding="utf-8"))
        profiles = json.loads((ROOT / "compatibility/profiles.json").read_text(encoding="utf-8"))
        self.assertIn('command: "inspect_tools"', ipc)
        self.assertIn('command: "list_cli_inventory"', ipc)
        self.assertIn("ToolInspectionDto", ipc)
        self.assertIn("CliInventoryDto", ipc)
        self.assertIn("engine_tools: false", ipc)
        self.assertIn("engine_cli: false", ipc)
        self.assertIn("live_execution: false", ipc)
        self.assertIn("InspectTools", rust_ipc)
        self.assertIn("ListCliInventory", rust_ipc)
        self.assertIn("assert_eq!(capabilities.commands.len(), 34)", rust_ipc)
        self.assertNotIn("assert_eq!(capabilities.commands.len(), 32)", rust_ipc)
        self.assertNotIn("assert_eq!(capabilities.commands.len(), 28)", rust_ipc)
        self.assertIn("inspect_tools", library)
        self.assertIn("list_cli_inventory", library)
        self.assertIn("empty_tool_inspection", library)
        self.assertIn("empty_cli_inventory", library)
        self.assertIn("ENGINE_TOOLS_NOT_OWNED", library)
        self.assertIn("ENGINE_CLI_NOT_OWNED", library)
        self.assertIn("SEARCH_IDENTITY", library)
        self.assertIn("FETCH_IDENTITY", library)
        self.assertIn("CALL_TOOL_IDENTITY", library)
        self.assertIn("ToolsCenterPanel", app)
        self.assertIn("CliInventoryPanel", app)
        self.assertIn("inspect_tools", app)
        self.assertIn("list_cli_inventory", app)
        self.assertIn("toolsEmptyTitle", catalog)
        self.assertIn("toolsErrorTitle", catalog)
        self.assertIn("toolsReadyTitle", catalog)
        self.assertIn("cliEmptyTitle", catalog)
        self.assertIn("cliErrorTitle", catalog)
        self.assertIn("cliReadyTitle", catalog)
        self.assertIn("工具", catalog)
        self.assertIn("CLI 任务中心", catalog)
        self.assertIn("call_tool", catalog)
        self.assertNotIn("dangerouslySetInnerHTML", app)
        self.assertNotIn("innerHTML", app)
        self.assertNotIn("start_supervisor", app)
        self.assertNotIn("callTool", app)
        self.assertNotIn("engine_worker.py", app)
        self.assertNotIn("engine_worker.py", rust_ipc)
        self.assertNotIn('command: "call_tool"', ipc)
        self.assertNotIn('{ command: "search"; args', ipc)
        self.assertNotIn('{ command: "fetch"; args', ipc)
        self.assertNotIn('{ command: "tools/call"; args', ipc)
        for name in deps:
            self.assertNotIn("vis", name.lower())
            self.assertNotIn("ajv", name.lower())
        self.assertIn(".tool-list", styles)
        self.assertIn(".cli-list", styles)
        self.assertIn("bmdock-t27", rust_ipc)
        self.assertNotIn(
            "inspect_tools",
            (ROOT / "apps/bmdock-desktop/src/shell.ts").read_text(encoding="utf-8"),
        )
        self.assertNotIn(
            "list_cli_inventory",
            (ROOT / "apps/bmdock-desktop/src/shell.ts").read_text(encoding="utf-8"),
        )
        self.assertNotIn("start_supervisor", rust_ipc)
        self.assertEqual(len(profiles["engines"]["release"]["expected_tools"]), 21)
        self.assertEqual(len(profiles["engines"]["main-preview"]["expected_tools"]), 27)
        self.assertIn("search", profiles["engines"]["release"]["expected_tools"])
        self.assertIn("fetch", profiles["engines"]["release"]["expected_tools"])
        self.assertNotEqual("search", "fetch")
        self.assertFalse(leaves["live_official_cli_execution"])
        self.assertFalse(leaves["engine_cli"])
        release_leaves = [tuple(path) for path in leaves["profiles"]["release"]["leaves"]]
        preview_leaves = [tuple(path) for path in leaves["profiles"]["main-preview"]["leaves"]]
        self.assertIn(("bm", "cloud", "login"), release_leaves)
        self.assertNotIn(("cloud",), release_leaves)
        self.assertIn(("bm", "cloud", "bisync"), preview_leaves)
        self.assertNotEqual(len(release_leaves), len(preview_leaves))
        allowlisted = "已列入允许列（allowlisted）"
        denied = "拒绝/未验证（denied）"
        self.assertIn(allowlisted, catalog)
        self.assertIn(denied, catalog)
        self.assertNotEqual(allowlisted, denied)

    def test_import_and_maintenance_ui_is_fixture_owned_not_official_extras(self):
        app = (ROOT / "apps/bmdock-desktop/src/App.tsx").read_text(encoding="utf-8")
        ipc = (ROOT / "apps/bmdock-desktop/src/ipc.ts").read_text(encoding="utf-8")
        rust_ipc = (ROOT / "apps/bmdock-desktop/src-tauri/src/ipc.rs").read_text(encoding="utf-8")
        library = (ROOT / "apps/bmdock-desktop/src-tauri/src/library.rs").read_text(encoding="utf-8")
        catalog = (ROOT / "apps/bmdock-desktop/src/i18n.ts").read_text(encoding="utf-8")
        styles = (ROOT / "apps/bmdock-desktop/src/styles.css").read_text(encoding="utf-8")
        package = json.loads((ROOT / "apps/bmdock-desktop/package.json").read_text(encoding="utf-8"))
        deps = {**package.get("dependencies", {}), **package.get("devDependencies", {})}
        self.assertIn('command: "import_notes"', ipc)
        self.assertIn("ImportResultDto", ipc)
        self.assertIn("engine_import: false", ipc)
        self.assertIn("ImportNotes", rust_ipc)
        self.assertIn("assert_eq!(capabilities.commands.len(), 34)", rust_ipc)
        self.assertNotIn("assert_eq!(capabilities.commands.len(), 32)", rust_ipc)
        self.assertIn("import_notes", library)
        self.assertIn("empty_import_result", library)
        self.assertIn("ENGINE_IMPORT_NOT_OWNED", library)
        self.assertIn("OFFICIAL_IMPORT_UNVERIFIED", library)
        self.assertIn("POLICY_FILESYSTEM_SOURCE", library)
        self.assertIn("ImportPanel", app)
        self.assertIn("BackupPanel", app)
        self.assertIn("import_notes", app)
        self.assertIn("list_backups", app)
        self.assertIn("restore_fixture", app)
        self.assertIn('htmlFor="import-source-id"', app)
        self.assertIn('id="import-source-id"', app)
        self.assertIn("importEmptyTitle", catalog)
        self.assertIn("importErrorTitle", catalog)
        self.assertIn("importReadyTitle", catalog)
        self.assertIn("导入", catalog)
        self.assertIn("Extra / 文档摄取", catalog)
        self.assertIn("维护", catalog)
        self.assertIn("extras", catalog)
        self.assertNotIn("dangerouslySetInnerHTML", app)
        self.assertNotIn("innerHTML", app)
        self.assertNotIn("start_supervisor", app)
        self.assertNotIn("callTool", app)
        self.assertNotIn('command: "call_tool"', ipc)
        self.assertNotEqual("import_notes", "restore_fixture")
        for name in deps:
            self.assertNotIn("vis", name.lower())
            self.assertNotIn("ajv", name.lower())
        self.assertIn(".import-list", styles)
        self.assertIn("bmdock-t28", rust_ipc)
        self.assertIn("import_notes_envelope_is_accepted_unverified_and_does_not_write", rust_ipc)
        self.assertNotIn(
            "import_notes",
            (ROOT / "apps/bmdock-desktop/src/shell.ts").read_text(encoding="utf-8"),
        )
        self.assertNotIn("start_supervisor", rust_ipc)
        self.assertIn("scanned_user_obsidian_vault", rust_ipc)
        disk = "观察分类：已核对物理文件正文"
        envelope = "观察分类：仅信封成功，不能当作磁盘证据"
        empty = "观察分类：源中没有可导入的 Markdown"
        self.assertIn(disk, catalog)
        self.assertIn(envelope, catalog)
        self.assertIn(empty, catalog)
        self.assertNotEqual(disk, envelope)


    def test_api_cli_audit_lists_named_gaps_not_full_coverage(self):
        app = (ROOT / "apps/bmdock-desktop/src/App.tsx").read_text(encoding="utf-8")
        ipc = (ROOT / "apps/bmdock-desktop/src/ipc.ts").read_text(encoding="utf-8")
        rust_ipc = (ROOT / "apps/bmdock-desktop/src-tauri/src/ipc.rs").read_text(encoding="utf-8")
        library = (ROOT / "apps/bmdock-desktop/src-tauri/src/library.rs").read_text(encoding="utf-8")
        catalog = (ROOT / "apps/bmdock-desktop/src/i18n.ts").read_text(encoding="utf-8")
        styles = (ROOT / "apps/bmdock-desktop/src/styles.css").read_text(encoding="utf-8")
        package = json.loads((ROOT / "apps/bmdock-desktop/package.json").read_text(encoding="utf-8"))
        deps = {**package.get("dependencies", {}), **package.get("devDependencies", {})}
        leaves = json.loads((ROOT / "compatibility/cli-leaves.json").read_text(encoding="utf-8"))
        profiles = json.loads((ROOT / "compatibility/profiles.json").read_text(encoding="utf-8"))
        self.assertIn('command: "inspect_api_audit"', ipc)
        self.assertIn("ApiAuditDto", ipc)
        self.assertIn("full_api_coverage: false", ipc)
        self.assertIn("semantic_enabled: false", ipc)
        self.assertIn("model_loaded: false", ipc)
        self.assertIn("InspectApiAudit", rust_ipc)
        self.assertIn("assert_eq!(capabilities.commands.len(), 34)", rust_ipc)
        self.assertNotIn("assert_eq!(capabilities.commands.len(), 32)", rust_ipc)
        self.assertIn("inspect_api_audit", library)
        self.assertIn("empty_api_audit", library)
        self.assertIn("ENGINE_AUDIT_NOT_OWNED", library)
        self.assertIn("OFFICIAL_API_COVERAGE_UNVERIFIED", library)
        self.assertIn("CAPABILITY_SEMANTIC", library)
        self.assertIn("CAPABILITY_EXTRAS_INGEST", library)
        self.assertIn("CAPABILITY_CLOUD", library)
        self.assertIn("CAPABILITY_LIVE_MCP", library)
        self.assertIn("CAPABILITY_OFFICIAL_SCHEMA_MCP", library)
        self.assertIn("CAPABILITY_LIVE_CLI", library)
        self.assertIn("ApiAuditPanel", app)
        self.assertIn("inspect_api_audit", app)
        self.assertIn("auditEmptyTitle", catalog)
        self.assertIn("auditErrorTitle", catalog)
        self.assertIn("auditReadyTitle", catalog)
        self.assertIn("API/CLI 审计", catalog)
        self.assertIn("auditCoveragePresent", catalog)
        self.assertIn("auditCoverageMissing", catalog)
        self.assertIn("auditCoverageUnverified", catalog)
        self.assertIn("auditNotFullCoverage", catalog)
        self.assertNotIn("dangerouslySetInnerHTML", app)
        self.assertNotIn("innerHTML", app)
        self.assertNotIn("start_supervisor", app)
        self.assertNotIn("callTool", app)
        self.assertNotIn('command: "call_tool"', ipc)
        self.assertNotIn("engine_worker", rust_ipc)
        self.assertNotIn("just contract", app)
        for name in deps:
            self.assertNotIn("vis", name.lower())
            self.assertNotIn("ajv", name.lower())
        self.assertIn(".audit-list", styles)
        self.assertIn("bmdock-t29", rust_ipc)
        self.assertIn("inspect_api_audit_fixture_lists_named_gaps_without_mixing_profiles", rust_ipc)
        self.assertNotIn(
            "inspect_api_audit",
            (ROOT / "apps/bmdock-desktop/src/shell.ts").read_text(encoding="utf-8"),
        )
        self.assertNotIn("start_supervisor", rust_ipc)
        release_tools = profiles["engines"]["release"]["expected_tools"]
        preview_tools = profiles["engines"]["main-preview"]["expected_tools"]
        self.assertEqual(len(release_tools), 21)
        self.assertEqual(len(preview_tools), 27)
        self.assertNotEqual(len(release_tools), len(preview_tools))
        release_leaves = {tuple(path) for path in leaves["profiles"]["release"]["leaves"]}
        preview_leaves = {tuple(path) for path in leaves["profiles"]["main-preview"]["leaves"]}
        self.assertIn(("bm", "cloud", "login"), release_leaves)
        self.assertIn(("bm", "cloud", "bisync"), preview_leaves)
        self.assertNotIn(("cloud",), release_leaves)
        present = "已存在（present）"
        missing = "缺失（missing）"
        unverified = "未验证（unverified）"
        self.assertIn(present, catalog)
        self.assertIn(missing, catalog)
        self.assertIn(unverified, catalog)
        self.assertNotEqual(present, missing)
        self.assertNotEqual(present, unverified)


    def test_extras_and_document_ingestion_is_fixture_owned_not_official(self):
        app = (ROOT / "apps/bmdock-desktop/src/App.tsx").read_text(encoding="utf-8")
        ipc = (ROOT / "apps/bmdock-desktop/src/ipc.ts").read_text(encoding="utf-8")
        rust_ipc = (ROOT / "apps/bmdock-desktop/src-tauri/src/ipc.rs").read_text(encoding="utf-8")
        library = (ROOT / "apps/bmdock-desktop/src-tauri/src/library.rs").read_text(encoding="utf-8")
        catalog = (ROOT / "apps/bmdock-desktop/src/i18n.ts").read_text(encoding="utf-8")
        styles = (ROOT / "apps/bmdock-desktop/src/styles.css").read_text(encoding="utf-8")
        package = json.loads((ROOT / "apps/bmdock-desktop/package.json").read_text(encoding="utf-8"))
        deps = {**package.get("dependencies", {}), **package.get("devDependencies", {})}
        self.assertIn('command: "inspect_extras"', ipc)
        self.assertIn('command: "ingest_document"', ipc)
        self.assertIn("ExtrasCatalogDto", ipc)
        self.assertIn("IngestResultDto", ipc)
        self.assertIn("extras_enabled", ipc)
        self.assertIn("semantic_enabled: false", ipc)
        self.assertIn("model_loaded: false", ipc)
        self.assertIn("InspectExtras", rust_ipc)
        self.assertIn("IngestDocument", rust_ipc)
        self.assertIn("assert_eq!(capabilities.commands.len(), 34)", rust_ipc)
        self.assertNotIn("assert_eq!(capabilities.commands.len(), 32)", rust_ipc)
        self.assertIn("inspect_extras", library)
        self.assertIn("ingest_document", library)
        self.assertIn("empty_extras_catalog", library)
        self.assertIn("empty_ingest_result", library)
        self.assertIn("ENGINE_EXTRAS_NOT_OWNED", library)
        self.assertIn("OFFICIAL_EXTRAS_UNVERIFIED", library)
        self.assertIn("UNSUPPORTED_EXTRAS_ENABLED_WITHOUT_DISK", library)
        self.assertIn("POLICY_FILESYSTEM_EXTRA", library)
        self.assertIn("ExtrasPanel", app)
        self.assertIn("inspect_extras", app)
        self.assertIn("ingest_document", app)
        self.assertIn('htmlFor="extras-source-id"', app)
        self.assertIn('id="extras-source-id"', app)
        self.assertIn("extrasEmptyTitle", catalog)
        self.assertIn("extrasErrorTitle", catalog)
        self.assertIn("extrasReadyTitle", catalog)
        self.assertIn("Extra / 文档摄取", catalog)
        self.assertNotIn("dangerouslySetInnerHTML", app)
        self.assertNotIn("innerHTML", app)
        self.assertNotIn("start_supervisor", app)
        self.assertNotIn("callTool", app)
        self.assertNotIn('command: "call_tool"', ipc)
        self.assertNotEqual("ingest_document", "import_notes")
        for name in deps:
            self.assertNotIn("vis", name.lower())
            self.assertNotIn("ajv", name.lower())
        self.assertIn(".extras-list", styles)
        self.assertIn("bmdock-t30", rust_ipc)
        self.assertIn("inspect_extras_fixture_hits_match_physical_utf8", rust_ipc)
        self.assertNotIn(
            "inspect_extras",
            (ROOT / "apps/bmdock-desktop/src/shell.ts").read_text(encoding="utf-8"),
        )
        self.assertNotIn(
            "ingest_document",
            (ROOT / "apps/bmdock-desktop/src/shell.ts").read_text(encoding="utf-8"),
        )
        self.assertNotIn("start_supervisor", rust_ipc)
        disk = "观察分类：已核对物理文件正文"
        envelope = "观察分类：仅信封成功，不能当作磁盘证据"
        empty = "观察分类：没有可列出的 extra"
        self.assertIn(disk, catalog)
        self.assertIn(envelope, catalog)
        self.assertIn(empty, catalog)
        self.assertNotEqual(disk, envelope)
        self.assertIn("extras_enabled=false", catalog)
        self.assertIn("PDF/Office", catalog)


if __name__ == "__main__":
    unittest.main()
