from __future__ import annotations

import json
from pathlib import Path
import unittest


ROOT = Path(__file__).resolve().parents[1]


def recipe_body(justfile: str, name: str) -> str:
    lines = justfile.splitlines()
    body: list[str] = []
    capturing = False
    for line in lines:
        if capturing:
            if line.startswith("#") or line.startswith(" ") or line.startswith("\t") or line.strip() == "":
                body.append(line)
                continue
            break
        if line == f"{name}:" or line.startswith(f"{name}:"):
            capturing = True
    return "\n".join(body)


class DesktopShellTests(unittest.TestCase):
    def test_html_lang_is_zh_cn(self):
        html = (ROOT / "apps/bmdock-desktop/index.html").read_text(encoding="utf-8")
        self.assertIn('lang="zh-CN"', html)

    def test_just_dev_switches_to_tauri_and_build_stays_probe(self):
        justfile = (ROOT / "justfile").read_text(encoding="utf-8")
        dev = recipe_body(justfile, "dev")
        build = recipe_body(justfile, "build")
        contract = recipe_body(justfile, "contract")
        contract_main = recipe_body(justfile, "contract-main")
        tauri_dev = recipe_body(justfile, "tauri-dev")
        tauri_build = recipe_body(justfile, "tauri-build")
        self.assertIn("tauri-dev", dev)
        self.assertNotIn('main(["dev"', dev)
        self.assertIn('main(["build"])', build)
        self.assertNotIn("tauri", build.lower())
        self.assertIn('main(["contract", "release"])', contract)
        self.assertIn('main(["contract", "main-preview"])', contract_main)
        self.assertIn("tauri:dev", tauri_dev)
        self.assertIn("tauri:build", tauri_build)

    def test_agent_docs_match_just_dev_tauri_and_build_probe(self):
        for name in ("AGENTS.md", "CLAUDE.md"):
            text = (ROOT / name).read_text(encoding="utf-8")
            self.assertIn("just tauri-dev", text)
            self.assertIn("just tauri-build", text)
            self.assertIn("just contract", text)
            self.assertIn("just dev-main", text)
            self.assertRegex(
                text,
                r"(?is)just dev.{0,300}(tauri-dev|tauri 桌面|desktop shell|desktop layout)",
                msg=f"{name} must describe just dev as the Tauri desktop shell",
            )
            self.assertRegex(
                text,
                r"(?is)just build.{0,240}(bmdock-probe|g0 probe|g0 探针)",
                msg=f"{name} must describe just build as the G0 probe",
            )

    def test_ci_still_builds_g0_probe_via_just_build(self):
        workflow = (ROOT / ".github/workflows/ci.yml").read_text(encoding="utf-8")
        self.assertIn("just build", workflow)

    def test_chinese_nav_catalog_and_no_i18n_dependency(self):
        catalog = (ROOT / "apps/bmdock-desktop/src/i18n.ts").read_text(encoding="utf-8")
        self.assertIn('export const LOCALE = "zh-CN"', catalog)
        self.assertIn("工作台", catalog)
        self.assertIn("运行状态", catalog)
        self.assertIn("预检", catalog)
        self.assertIn("项目", catalog)
        self.assertIn("维护", catalog)
        self.assertIn("观察", catalog)
        self.assertIn("关系", catalog)
        self.assertIn("运行时", catalog)
        self.assertIn("说明", catalog)
        package = json.loads((ROOT / "apps/bmdock-desktop/package.json").read_text(encoding="utf-8"))
        deps = {**package.get("dependencies", {}), **package.get("devDependencies", {})}
        for name in deps:
            self.assertNotIn("i18n", name.lower())

    def test_landmarks_empty_error_and_no_writes(self):
        app = (ROOT / "apps/bmdock-desktop/src/App.tsx").read_text(encoding="utf-8")
        shell = (ROOT / "apps/bmdock-desktop/src/shell.ts").read_text(encoding="utf-8")
        styles = (ROOT / "apps/bmdock-desktop/src/styles.css").read_text(encoding="utf-8")
        catalog = (ROOT / "apps/bmdock-desktop/src/i18n.ts").read_text(encoding="utf-8")
        main = (ROOT / "apps/bmdock-desktop/src/main.tsx").read_text(encoding="utf-8")
        self.assertIn("<header", app)
        self.assertIn("<nav", app)
        self.assertIn("<main", app)
        self.assertIn('href="#main"', app)
        self.assertIn("skip-link", app)
        self.assertIn("aria-current", app)
        self.assertIn("aria-label", app)
        self.assertIn('data-state="empty"', app)
        self.assertIn('data-state="error"', app)
        self.assertIn("workbenchErrorTitle", app)
        self.assertIn("capabilities.policy.project", app)
        self.assertIn(":focus-visible", styles)
        self.assertIn("document.documentElement.lang", main)
        self.assertIn("emptyBadge", catalog)
        self.assertIn("errorBadge", catalog)
        self.assertIn("unexpectedCapabilities", catalog)
        self.assertIn("unexpectedRuntime", catalog)
        self.assertIn("unexpectedCatalog", catalog)
        self.assertIn("unexpectedPreflight", catalog)
        self.assertIn("unexpectedDiscovery", catalog)
        self.assertIn("unexpectedBackups", catalog)
        self.assertIn("unexpectedRestore", catalog)
        self.assertIn("unexpectedWindowsRuntime", catalog)
        self.assertIn("unexpectedDraft", catalog)
        self.assertIn("unexpectedCrud", catalog)
        self.assertIn("unexpectedRelations", catalog)
        self.assertIn("unexpectedDrain", catalog)
        self.assertIn("runtimeDrainStart", catalog)
        self.assertIn("runtimeDrainIdle", catalog)
        self.assertIn("runtimeDrainDraining", catalog)
        self.assertIn("draftEmptyTitle", catalog)
        self.assertIn("draftErrorTitle", catalog)
        self.assertIn("draftReadyTitle", catalog)
        self.assertIn("draftIdentifierLabel", catalog)
        self.assertIn("draftBodyLabel", catalog)
        self.assertIn("contentSafetyTitle", catalog)
        self.assertIn("contentSafetyExecutedNo", catalog)
        self.assertIn("contentSafetyImeUnverified", catalog)
        self.assertIn("contentSafetyHelpNotT39", catalog)
        self.assertIn("draftSave", catalog)
        self.assertIn("draftReload", catalog)
        self.assertIn("draftSessionDirty", catalog)
        self.assertIn("draftSessionDisk", catalog)
        self.assertIn("draftEnginePersistedLabel", catalog)
        self.assertIn("crudEmptyTitle", catalog)
        self.assertIn("crudErrorTitle", catalog)
        self.assertIn("crudReadyTitle", catalog)
        self.assertIn("crudWrite", catalog)
        self.assertIn("crudEdit", catalog)
        self.assertIn("crudMove", catalog)
        self.assertIn("crudDelete", catalog)
        self.assertIn("crudDeleteConfirm", catalog)
        self.assertIn("windowsEmptyTitle", catalog)
        self.assertIn("windowsErrorTitle", catalog)
        self.assertIn("windowsReadyTitle", catalog)
        self.assertIn("windowsObservedTitle", catalog)
        self.assertIn("windowsUnverifiedTitle", catalog)
        self.assertIn("discoveryEmptyTitle", catalog)
        self.assertIn("backupsEmptyTitle", catalog)
        self.assertIn("backupsErrorTitle", catalog)
        self.assertIn("backupsReadyTitle", catalog)
        self.assertIn("backupsRestore", catalog)
        self.assertIn("projectsEmptyNoneSelectedTitle", catalog)
        self.assertIn("projectsEmptyNoneFoundTitle", catalog)
        self.assertIn("projectsErrorTitle", catalog)
        self.assertIn("projectsReadyTitle", catalog)
        self.assertIn('t("unexpectedCapabilities")', shell)
        self.assertIn('t("unexpectedRuntime")', shell)
        self.assertIn("get_capabilities", shell)
        self.assertIn("get_runtime_state", shell)
        self.assertIn("list_projects", shell)
        self.assertIn("run_preflight", shell)
        self.assertIn("discover_config", shell)
        self.assertNotIn("list_tree", shell)
        self.assertNotIn("read_note", shell)
        self.assertNotIn("list_backups", shell)
        self.assertNotIn("restore_fixture", shell)
        self.assertNotIn("inspect_windows_runtime", shell)
        self.assertNotIn("save_draft", shell)
        self.assertNotIn("load_draft", shell)
        self.assertNotIn("write_note", shell)
        self.assertNotIn("edit_note", shell)
        self.assertNotIn("move_note", shell)
        self.assertNotIn("delete_note", shell)
        self.assertNotIn("list_relations", shell)
        self.assertNotIn("begin_shutdown", shell)
        self.assertIn('t("unexpectedPreflight")', shell)
        self.assertIn('t("unexpectedDiscovery")', shell)
        self.assertIn('t("unexpectedCatalog")', shell)
        self.assertNotIn("select_project", shell)
        self.assertNotIn("callTool", shell)
        self.assertNotIn("call_tool", shell)
        self.assertNotIn("start_supervisor", shell)
        self.assertNotIn("stop_supervisor", shell)
        self.assertIn("select_project", app)
        self.assertNotIn("callTool", app)
        self.assertNotIn("start_supervisor", app)
        self.assertNotIn("stop_supervisor", app)
        self.assertIn("preflight", app)
        self.assertIn("projects", app)
        self.assertIn("backups", app)
        self.assertIn("discoveryEmptyTitle", app)
        self.assertIn("projectsEmptyNoneSelectedTitle", app)
        self.assertIn("backupsEmptyTitle", app)
        self.assertIn("backupsRestore", app)
        self.assertIn('id.startsWith("fixture-")', app)
        self.assertIn("workbenchLoadMore", app)
        self.assertIn("workbenchPreviewTitle", app)
        self.assertIn("list_tree", app)
        self.assertIn("read_note", app)
        self.assertIn("list_relations", app)
        self.assertIn("list_backups", app)
        self.assertIn("restore_fixture", app)
        self.assertIn("inspect_windows_runtime", app)
        self.assertIn("save_draft", app)
        self.assertIn("load_draft", app)
        self.assertIn("write_note", app)
        self.assertIn("edit_note", app)
        self.assertIn("move_note", app)
        self.assertIn("delete_note", app)
        self.assertIn("begin_shutdown", app)
        self.assertIn("draftEmptyTitle", app)
        self.assertIn("draftErrorTitle", app)
        self.assertIn("draftReadyTitle", app)
        self.assertIn("contentSafetyTitle", app)
        self.assertIn('data-preview="text"', app)
        self.assertIn('data-executed="false"', app)
        self.assertIn("classifyBody", app)
        self.assertIn("crudEmptyTitle", app)
        self.assertIn("crudErrorTitle", app)
        self.assertIn("crudReadyTitle", app)
        self.assertIn('htmlFor="draft-identifier"', app)
        self.assertIn('htmlFor="draft-body"', app)
        self.assertIn('id="draft-identifier"', app)
        self.assertIn('id="draft-body"', app)
        self.assertIn('htmlFor="crud-identifier"', app)
        self.assertIn('htmlFor="crud-title"', app)
        self.assertIn('htmlFor="crud-body"', app)
        self.assertIn('htmlFor="crud-destination"', app)
        self.assertIn('id="crud-identifier"', app)
        self.assertIn('id="crud-body"', app)
        self.assertIn("<textarea", app)
        self.assertIn("draft-body", app)
        self.assertIn("crud-body", app)
        self.assertIn("draftSessionDirty", app)
        self.assertIn("engine_persisted", app)
        self.assertIn("copyFixtureRoute", app)
        self.assertIn("windowsEmptyTitle", app)
        self.assertIn("windowsErrorTitle", app)
        self.assertIn("windowsReadyTitle", app)
        self.assertIn("windowsObservedTitle", app)
        self.assertIn("windowsUnverifiedTitle", app)
        self.assertIn("copyFixtureRoute", app)
        self.assertIn("nextCursor", app)
        self.assertIn("note-body", app)
        self.assertIn("<pre", app)
        self.assertNotIn("dangerouslySetInnerHTML", app)
        self.assertNotIn("innerHTML", app)
        ipc = (ROOT / "apps/bmdock-desktop/src/ipc.ts").read_text(encoding="utf-8")
        self.assertIn("run_preflight", ipc)
        self.assertIn("discover_config", ipc)
        self.assertIn("list_projects", ipc)
        self.assertIn("list_tree", ipc)
        self.assertIn("read_note", ipc)
        self.assertIn("list_relations", ipc)
        self.assertIn("list_backups", ipc)
        self.assertIn("restore_fixture", ipc)
        self.assertIn("inspect_windows_runtime", ipc)
        self.assertIn("save_draft", ipc)
        self.assertIn("load_draft", ipc)
        self.assertIn("write_note", ipc)
        self.assertIn("edit_note", ipc)
        self.assertIn("move_note", ipc)
        self.assertIn("delete_note", ipc)
        self.assertIn("begin_shutdown", ipc)
        self.assertIn("engine_persisted", ipc)
        self.assertIn("webview2_files_present", ipc)
        self.assertIn("webview2_session_verified", ipc)
        self.assertIn("job_object_assigned", ipc)
        self.assertIn("job_object_api_documented", ipc)
        self.assertIn("installer_bundle_active", ipc)
        self.assertIn("ExplicitRouteArgs", ipc)
        self.assertIn("copyFixtureRoute", ipc)
        self.assertNotIn('command: "call_tool"', ipc)
        self.assertNotIn('"call_tool"', ipc)
        self.assertNotIn('command: "search_notes"', ipc)
        self.assertIn('command: "write_note"', ipc)
        self.assertIn('command: "edit_note"', ipc)
        self.assertIn('command: "move_note"', ipc)
        self.assertIn('command: "delete_note"', ipc)
        self.assertIn("host.engine_spawned", app)
        self.assertIn("host.files_written", app)
        self.assertIn("arbitrary_paths_allowed", ipc)
        self.assertIn("raw_call_tool_allowed", ipc)
        self.assertIn("implicit_current_project_writes", ipc)
        self.assertIn("cross_project_search_allowed", ipc)
        self.assertIn("cloud_or_credential_required", ipc)
        self.assertIn("bmdock-workspace", ipc)
        self.assertIn("bmdock-fixture", ipc)
        self.assertIn("scanned_user_obsidian_vault", ipc)
        self.assertIn("scanned_user_basic_memory_home", ipc)

    def test_windows_runtime_prototype_is_unsigned_and_unbundled(self):
        conf = json.loads(
            (ROOT / "apps/bmdock-desktop/src-tauri/tauri.conf.json").read_text(encoding="utf-8")
        )
        self.assertFalse(conf["bundle"]["active"])
        ipc = (ROOT / "apps/bmdock-desktop/src/ipc.ts").read_text(encoding="utf-8")
        rust = (ROOT / "apps/bmdock-desktop/src-tauri/src/windows_runtime.rs").read_text(
            encoding="utf-8"
        )
        app = (ROOT / "apps/bmdock-desktop/src/App.tsx").read_text(encoding="utf-8")
        self.assertIn("inspect_windows_runtime", ipc)
        self.assertIn("webview2_session_verified: false", rust)
        self.assertIn("job_object_assigned: false", rust)
        self.assertIn("compiled exe / npm build / cargo test are not a native GUI", rust)
        self.assertIn("WebView2 files present is not a WebView2 session", rust)
        self.assertIn("Job Object API/docs is not proof a job was created", rust)
        self.assertIn("inspect_dto_is_not_just_contract", rust)
        self.assertIn("inspect_dto_is_not_t12_fixture_restore", rust)
        self.assertIn("windowsObservedTitle", app)
        self.assertIn("windowsUnverifiedTitle", app)
        self.assertNotIn("dangerouslySetInnerHTML", app)
        self.assertNotIn("start_supervisor", app)
        rust_ipc = (ROOT / "apps/bmdock-desktop/src-tauri/src/ipc.rs").read_text(encoding="utf-8")
        self.assertIn("InspectWindowsRuntime", rust_ipc)
        self.assertIn("SaveDraft", rust_ipc)
        self.assertIn("LoadDraft", rust_ipc)
        self.assertIn("WriteNote", rust_ipc)
        self.assertIn("EditNote", rust_ipc)
        self.assertIn("MoveNote", rust_ipc)
        self.assertIn("DeleteNote", rust_ipc)
        self.assertIn("ListRelations", rust_ipc)
        self.assertIn("BeginShutdown", rust_ipc)
        self.assertIn("assert_eq!(capabilities.commands.len(), 19)", rust_ipc)
        self.assertNotIn("assert_eq!(capabilities.commands.len(), 18)", rust_ipc)
        self.assertNotIn("assert_eq!(capabilities.commands.len(), 17)", rust_ipc)
        self.assertNotIn("assert_eq!(capabilities.commands.len(), 13)", rust_ipc)

    def test_draft_editor_session_is_not_engine_write(self):
        app = (ROOT / "apps/bmdock-desktop/src/App.tsx").read_text(encoding="utf-8")
        ipc = (ROOT / "apps/bmdock-desktop/src/ipc.ts").read_text(encoding="utf-8")
        rust_ipc = (ROOT / "apps/bmdock-desktop/src-tauri/src/ipc.rs").read_text(encoding="utf-8")
        drafts = (ROOT / "apps/bmdock-desktop/src-tauri/src/drafts.rs").read_text(encoding="utf-8")
        catalog = (ROOT / "apps/bmdock-desktop/src/i18n.ts").read_text(encoding="utf-8")
        styles = (ROOT / "apps/bmdock-desktop/src/styles.css").read_text(encoding="utf-8")
        self.assertIn("save_draft", ipc)
        self.assertIn("load_draft", ipc)
        self.assertIn('command: "save_draft"', ipc)
        self.assertIn('command: "load_draft"', ipc)
        self.assertIn('command: "write_note"', ipc)
        self.assertNotIn("callTool", app)
        self.assertIn("write_note", app)
        self.assertIn("save_draft", app)
        self.assertIn("command: \"save_draft\"", app)
        self.assertNotIn("start_supervisor", app)
        self.assertNotIn("stop_supervisor", app)
        self.assertNotIn("dangerouslySetInnerHTML", app)
        self.assertIn("<textarea", app)
        self.assertIn('htmlFor="draft-body"', app)
        self.assertIn("engine_persisted: false", drafts)
        self.assertIn("engine_persisted", rust_ipc)
        self.assertIn("UNSUPPORTED_DRAFT_UNAVAILABLE", drafts)
        self.assertIn("engine/draft store unavailable", drafts)
        self.assertNotIn("engine/library unavailable", drafts)
        self.assertIn("[[欢迎]]", rust_ipc)
        self.assertIn("bmdock-t14", drafts)
        self.assertIn("bmdock-t15", rust_ipc)
        self.assertIn("envelope_is_not_disk_proof", drafts)
        self.assertIn("DraftClass::DiskVerified", rust_ipc)
        self.assertIn("DraftClass::AcceptedUnverified", rust_ipc)
        self.assertIn("draftSessionDirty", catalog)
        self.assertIn("draftSessionDisk", catalog)
        self.assertIn("draftEnginePersistedLabel", catalog)
        self.assertIn(":focus-visible", styles)
        self.assertIn(".draft-body", styles)

    def test_note_crud_is_typed_fixture_only_and_not_raw_call_tool(self):
        app = (ROOT / "apps/bmdock-desktop/src/App.tsx").read_text(encoding="utf-8")
        ipc = (ROOT / "apps/bmdock-desktop/src/ipc.ts").read_text(encoding="utf-8")
        rust_ipc = (ROOT / "apps/bmdock-desktop/src-tauri/src/ipc.rs").read_text(encoding="utf-8")
        library = (ROOT / "apps/bmdock-desktop/src-tauri/src/library.rs").read_text(encoding="utf-8")
        catalog = (ROOT / "apps/bmdock-desktop/src/i18n.ts").read_text(encoding="utf-8")
        styles = (ROOT / "apps/bmdock-desktop/src/styles.css").read_text(encoding="utf-8")
        self.assertIn('command: "write_note"', ipc)
        self.assertIn('command: "edit_note"', ipc)
        self.assertIn('command: "move_note"', ipc)
        self.assertIn('command: "delete_note"', ipc)
        self.assertNotIn('command: "call_tool"', ipc)
        self.assertNotIn("callTool", app)
        self.assertNotIn("start_supervisor", app)
        self.assertNotIn("stop_supervisor", app)
        self.assertNotIn("dangerouslySetInnerHTML", app)
        self.assertIn("crudDeleteConfirm", app)
        self.assertIn("isFixtureNoteIdentifier", app)
        self.assertIn("copyFixtureRoute", app)
        self.assertIn("engine_persisted: false", library)
        self.assertIn("UNSUPPORTED_LIBRARY_UNAVAILABLE", library)
        self.assertIn("engine/library unavailable", library)
        self.assertIn("UNSUPPORTED_MOVE_DESTINATION_EXISTS", library)
        self.assertIn("sequential dest-exists is unsupported and is not T16", library)
        self.assertNotIn("concurrent overwrite remains UNVERIFIED", library)
        self.assertIn("bmdock-t15", library)
        self.assertIn("NoteCrudClass::DiskVerified", rust_ipc)
        self.assertIn("NoteCrudClass::AcceptedUnverified", rust_ipc)
        self.assertIn("[[欢迎]]", rust_ipc)
        self.assertIn("implicit_current_project_writes", rust_ipc)
        self.assertIn("crudWrite", catalog)
        self.assertIn("crudEdit", catalog)
        self.assertIn("crudMove", catalog)
        self.assertIn("crudDeleteConfirm", catalog)
        self.assertIn(".crud-body", styles)
        self.assertIn("command: \"save_draft\"", app)
        self.assertIn("command: \"write_note\"", app)

    def test_conflict_and_timeout_unknown_stay_distinct(self):
        app = (ROOT / "apps/bmdock-desktop/src/App.tsx").read_text(encoding="utf-8")
        ipc = (ROOT / "apps/bmdock-desktop/src/ipc.ts").read_text(encoding="utf-8")
        rust_ipc = (ROOT / "apps/bmdock-desktop/src-tauri/src/ipc.rs").read_text(encoding="utf-8")
        conflict = (ROOT / "apps/bmdock-desktop/src-tauri/src/conflict.rs").read_text(
            encoding="utf-8"
        )
        library = (ROOT / "apps/bmdock-desktop/src-tauri/src/library.rs").read_text(encoding="utf-8")
        catalog = (ROOT / "apps/bmdock-desktop/src/i18n.ts").read_text(encoding="utf-8")
        styles = (ROOT / "apps/bmdock-desktop/src/styles.css").read_text(encoding="utf-8")
        shell = (ROOT / "apps/bmdock-desktop/src/shell.ts").read_text(encoding="utf-8")
        self.assertIn("library::NoteCrudClass::Conflict", rust_ipc)
        self.assertIn("NoteCrudClass::Conflict", conflict)
        self.assertIn("| \"conflict\"", ipc)
        self.assertIn('export type ErrorCategory = "policy" | "schema" | "unsupported"', ipc)
        self.assertNotIn('ErrorCategory = "policy" | "schema" | "unsupported" | "timeout_unknown"', ipc)
        self.assertIn('export type FailureKind = "policy" | "transport" | "timeout_unknown" | "process" | "unverified"', ipc)
        self.assertIn("auto_retry_non_idempotent_write", conflict)
        self.assertIn("should_auto_retry_non_idempotent_write", conflict)
        self.assertIn("OS_FILESYSTEM_RACE_UNVERIFIED", conflict)
        self.assertIn("RECOVERY_NOT_T16", conflict)
        self.assertIn("not an OS file lock", conflict)
        self.assertIn("crudObservationConflict", app)
        self.assertIn("failureTimeoutUnknown", app)
        self.assertIn("crudObservationDisk", app)
        self.assertIn("crudObservationUnverified", app)
        self.assertIn("coordination-legend", app)
        self.assertIn("data-observation", app)
        self.assertIn("crudTimeoutUnknownLabel", app)
        self.assertIn("crudRecoveryNotT17", app)
        self.assertNotIn("dangerouslySetInnerHTML", app)
        self.assertNotIn("start_supervisor", app)
        self.assertNotIn("stop_supervisor", app)
        self.assertIn('t("failureTimeoutUnknown")', shell)
        self.assertIn("crudObservationConflict", catalog)
        self.assertIn("failureTimeoutUnknown", catalog)
        self.assertNotEqual(catalog.count("crudObservationConflict"), 0)
        conflict_label = '观察分类：同目标冲突，不是磁盘已核对，也不是超时未知'
        disk_label = "观察分类：已核对物理笔记文件"
        unverified_label = "观察分类：仅信封成功，不能当作磁盘证据"
        timeout_label = "超时未知"
        self.assertIn(conflict_label, catalog)
        self.assertIn(disk_label, catalog)
        self.assertIn(unverified_label, catalog)
        self.assertIn(timeout_label, catalog)
        self.assertNotEqual(conflict_label, timeout_label)
        self.assertNotEqual(conflict_label, disk_label)
        self.assertNotEqual(conflict_label, unverified_label)
        self.assertNotEqual(timeout_label, disk_label)
        self.assertIn("sequential dest-exists is unsupported and is not T16", library)
        self.assertIn("Conflict", rust_ipc)
        self.assertIn("refuse_auto_retry", rust_ipc)
        self.assertIn(".coordination-legend", styles)
        self.assertIn("mod conflict", (ROOT / "apps/bmdock-desktop/src-tauri/src/main.rs").read_text(encoding="utf-8"))

    def test_graceful_exit_drain_is_distinct_and_does_not_start_supervisor(self):
        app = (ROOT / "apps/bmdock-desktop/src/App.tsx").read_text(encoding="utf-8")
        ipc = (ROOT / "apps/bmdock-desktop/src/ipc.ts").read_text(encoding="utf-8")
        rust_ipc = (ROOT / "apps/bmdock-desktop/src-tauri/src/ipc.rs").read_text(encoding="utf-8")
        drain = (ROOT / "apps/bmdock-desktop/src-tauri/src/drain.rs").read_text(encoding="utf-8")
        catalog = (ROOT / "apps/bmdock-desktop/src/i18n.ts").read_text(encoding="utf-8")
        styles = (ROOT / "apps/bmdock-desktop/src/styles.css").read_text(encoding="utf-8")
        shell = (ROOT / "apps/bmdock-desktop/src/shell.ts").read_text(encoding="utf-8")
        main = (ROOT / "apps/bmdock-desktop/src-tauri/src/main.rs").read_text(encoding="utf-8")
        self.assertIn('command: "begin_shutdown"', ipc)
        self.assertIn("host_drain", ipc)
        self.assertIn("idle_not_started", ipc)
        self.assertIn("inflight_unknown", ipc)
        self.assertIn("BeginShutdown", rust_ipc)
        self.assertIn("UNSUPPORTED_HOST_DRAINING", drain)
        self.assertIn("host is draining", drain)
        self.assertIn("FORCED_KILL_UNVERIFIED", drain)
        self.assertIn("JOB_OBJECT_UNVERIFIED", drain)
        self.assertIn("SLEEP_RESUME_UNVERIFIED", drain)
        self.assertIn("DISK_FAILURE_UNVERIFIED", drain)
        self.assertIn("T12_RESTORE_IS_NOT_T17_DRAIN", drain)
        self.assertIn("T16_CONFLICT_IS_NOT_T17_DRAIN", drain)
        self.assertIn("T07_FAKES_ARE_NOT_NATIVE_PROCESS_TREE", drain)
        self.assertIn("not a native process-tree", drain)
        self.assertIn("mod drain", main)
        self.assertIn("begin_shutdown", app)
        self.assertIn("runtimeDrainStart", app)
        self.assertIn("runtimeDrainIdleLabel", app)
        self.assertIn("runtimeDrainDrainingLabel", app)
        self.assertIn("runtimeDrainTimeoutUnknownLabel", app)
        self.assertIn("runtimeDrainConflictLabel", app)
        self.assertIn("data-drain", app)
        self.assertNotIn("dangerouslySetInnerHTML", app)
        self.assertNotIn("start_supervisor", app)
        self.assertNotIn("stop_supervisor", app)
        self.assertNotIn("begin_shutdown", shell)
        self.assertIn("drainPhaseLabel", shell)
        idle_label = "空闲（尚未排空）"
        draining_label = "正在排空（拒绝新的笔记写入）"
        timeout_label = "超时未知（运行状态失败分类）"
        conflict_label = "同目标冲突（工作台 CRUD，不是本排空收据）"
        self.assertIn(idle_label, catalog)
        self.assertIn(draining_label, catalog)
        self.assertIn(timeout_label, catalog)
        self.assertIn(conflict_label, catalog)
        self.assertNotEqual(idle_label, draining_label)
        self.assertNotEqual(idle_label, timeout_label)
        self.assertNotEqual(idle_label, conflict_label)
        self.assertNotEqual(draining_label, timeout_label)
        self.assertNotEqual(draining_label, conflict_label)
        self.assertNotEqual(timeout_label, conflict_label)
        self.assertIn(".drain-legend", styles)
        self.assertIn("assert_eq!(capabilities.commands.len(), 19)", rust_ipc)
        self.assertIn('| "conflict"', ipc)
        self.assertIn('export type ErrorCategory = "policy" | "schema" | "unsupported"', ipc)
        self.assertNotIn('ErrorCategory = "policy" | "schema" | "unsupported" | "timeout_unknown"', ipc)

    def test_editor_content_safety_and_windows_roundtrip(self):
        app = (ROOT / "apps/bmdock-desktop/src/App.tsx").read_text(encoding="utf-8")
        safety_ts = (ROOT / "apps/bmdock-desktop/src/contentSafety.ts").read_text(encoding="utf-8")
        catalog = (ROOT / "apps/bmdock-desktop/src/i18n.ts").read_text(encoding="utf-8")
        styles = (ROOT / "apps/bmdock-desktop/src/styles.css").read_text(encoding="utf-8")
        rust = (ROOT / "apps/bmdock-desktop/src-tauri/src/content_safety.rs").read_text(
            encoding="utf-8"
        )
        drafts = (ROOT / "apps/bmdock-desktop/src-tauri/src/drafts.rs").read_text(encoding="utf-8")
        library = (ROOT / "apps/bmdock-desktop/src-tauri/src/library.rs").read_text(encoding="utf-8")
        rust_ipc = (ROOT / "apps/bmdock-desktop/src-tauri/src/ipc.rs").read_text(encoding="utf-8")
        main = (ROOT / "apps/bmdock-desktop/src-tauri/src/main.rs").read_text(encoding="utf-8")
        self.assertIn("classifyBody", safety_ts)
        self.assertIn("executed: false", safety_ts)
        self.assertIn("<script>", safety_ts)
        self.assertIn("onerror=", safety_ts)
        self.assertIn("[[欢迎]]", safety_ts)
        self.assertIn("\\r\\n", safety_ts)
        self.assertIn("UNSAFE_HTML_WIKI_CRLF_BODY", rust)
        self.assertIn("persist_exact_utf8", rust)
        self.assertIn("crlf_normalized_to_lf", rust)
        self.assertIn("not disk_verified", rust)
        self.assertIn("UNVERIFIED", rust)
        self.assertIn("T39", rust)
        self.assertIn("persist_exact_utf8", drafts)
        self.assertIn("persist_exact_utf8", library)
        self.assertIn("unsafe_html_crlf_wiki_roundtrips_on_draft_and_note_paths", rust_ipc)
        self.assertIn("mod content_safety", main)
        self.assertIn("classifyBody", app)
        self.assertIn("<textarea", app)
        self.assertIn("<pre", app)
        self.assertIn('data-preview="text"', app)
        self.assertIn('data-executed="false"', app)
        self.assertIn('htmlFor="draft-body"', app)
        self.assertIn('htmlFor="crud-body"', app)
        self.assertIn('id="draft-body"', app)
        self.assertIn('id="crud-body"', app)
        self.assertNotIn("dangerouslySetInnerHTML", app)
        self.assertNotIn("innerHTML", app)
        self.assertNotIn("start_supervisor", app)
        self.assertNotIn("stop_supervisor", app)
        self.assertNotIn("callTool", app)
        self.assertIn("contentSafetyTitle", catalog)
        self.assertIn("contentSafetyExecutedNo", catalog)
        self.assertIn("contentSafetyImeUnverified", catalog)
        self.assertIn("contentSafetyHelpNotT39", catalog)
        self.assertIn("T39", catalog)
        self.assertIn(":focus-visible", styles)
        self.assertIn(".content-safety", styles)
        self.assertIn("C:\\Users\\someone\\vault\\note.md", rust_ipc)
        self.assertIn("looks_like_filesystem_path", library)
        self.assertIn("assert_eq!(capabilities.commands.len(), 19)", rust_ipc)

    def test_observation_and_relation_panel_is_fixture_wiki_links_not_engine_graph(self):
        app = (ROOT / "apps/bmdock-desktop/src/App.tsx").read_text(encoding="utf-8")
        ipc = (ROOT / "apps/bmdock-desktop/src/ipc.ts").read_text(encoding="utf-8")
        rust_ipc = (ROOT / "apps/bmdock-desktop/src-tauri/src/ipc.rs").read_text(encoding="utf-8")
        library = (ROOT / "apps/bmdock-desktop/src-tauri/src/library.rs").read_text(encoding="utf-8")
        catalog = (ROOT / "apps/bmdock-desktop/src/i18n.ts").read_text(encoding="utf-8")
        styles = (ROOT / "apps/bmdock-desktop/src/styles.css").read_text(encoding="utf-8")
        self.assertIn('command: "list_relations"', ipc)
        self.assertIn("RelationListDto", ipc)
        self.assertIn("engine_graph: false", ipc)
        self.assertIn("ListRelations", rust_ipc)
        self.assertIn("assert_eq!(capabilities.commands.len(), 19)", rust_ipc)
        self.assertIn("extract_wiki_link_identifiers", library)
        self.assertIn("ENGINE_GRAPH_NOT_OWNED", library)
        self.assertIn("RECENT_ACTIVITY_MCP_UNVERIFIED", library)
        self.assertIn("BUILD_CONTEXT_MCP_UNVERIFIED", library)
        self.assertIn("official recent_activity MCP remains UNVERIFIED", library)
        self.assertIn("official build_context MCP remains UNVERIFIED", library)
        self.assertIn("empty_relation_list", library)
        self.assertIn("ObservationPanel", app)
        self.assertIn("RelationPanel", app)
        self.assertIn("list_relations", app)
        self.assertIn("observationDisk", app)
        self.assertIn("observationConflict", app)
        self.assertIn("observationUnverified", app)
        self.assertIn("observationEmpty", app)
        self.assertIn("observationDistinctFromRelations", app)
        self.assertIn("relationsPermalinkNotPath", app)
        self.assertIn("relationsMcpUnverified", app)
        self.assertIn("relationsEmptyTitle", catalog)
        self.assertIn("observationReadyTitle", catalog)
        disk_label = "已核对磁盘（disk_verified）"
        unverified_label = "仅信封成功（accepted_unverified）"
        conflict_label = "同目标冲突（conflict）"
        empty_label = "空态（empty）"
        self.assertIn(disk_label, catalog)
        self.assertIn(unverified_label, catalog)
        self.assertIn(conflict_label, catalog)
        self.assertIn(empty_label, catalog)
        self.assertNotEqual(disk_label, conflict_label)
        self.assertNotEqual(unverified_label, conflict_label)
        self.assertNotEqual(empty_label, conflict_label)
        self.assertIn("观察", catalog)
        self.assertIn("关系", catalog)
        self.assertNotIn("dangerouslySetInnerHTML", app)
        self.assertNotIn("innerHTML", app)
        self.assertNotIn("start_supervisor", app)
        self.assertNotIn("callTool", app)
        self.assertNotIn('command: "recent_activity"', ipc)
        self.assertNotIn('command: "build_context"', ipc)
        self.assertNotIn('command: "call_tool"', ipc)
        self.assertIn(".relation-list", styles)
        self.assertIn(".observation-legend", styles)
        self.assertIn("bmdock-t19", rust_ipc)


if __name__ == "__main__":
    unittest.main()
